/* AI World Atlas v2 — capa incremental sobre la aplicación existente. */
(function(){
const LANG_KEY='aiWorldAtlasLanguageV1';
let currentLang=localStorage.getItem(LANG_KEY)||'es';
let activeEcoRegion='';
let radarData=[];

const I18N={
 es:{ecosystems:'Laboratorios y ecosistemas de IA',ecosystemsIntro:'Primero mostramos a quienes investigan, entrenan modelos o mantienen ecosistemas propios relevantes. Después separamos modelos, productos y aplicaciones construidas sobre esa tecnología.',allRegions:'Todo el mundo',open:'Abrir ↗',analysis:'Ver ficha',general:'Comparación de asistentes de propósito general',generalIntro:'Una comparación orientativa de productos generales. No existe una clasificación universal perfecta: revisa también sus fortalezas por especialidad.',apps:'Aplicaciones con inteligencia artificial',appsIntro:'Productos útiles que aportan valor mediante diseño, productividad, programación, contenido o automatización. Se muestran por separado cuando dependen principalmente de modelos de terceros.',learn:'Entender el ecosistema sin complicarlo',searchHint:'Prueba: “quiero hacer un video”, “necesito programar” o “quiero investigar”.',results:'resultados',official:'Sitio oficial',save:'Guardar',saved:'Guardada',discard:'Descartar',what:'Qué es',developer:'Quién lo desarrolla',origin:'País de origen',capabilities:'Qué puede hacer',strength:'En qué destaca',models:'Modelos o tecnología',research:'Investigación propia',ownModels:'Modelos propios',products:'Ecosistema / productos',useful:'Para quién resulta útil',examples:'Ejemplos de uso',availability:'Disponibilidad',pricing:'Modalidad',updated:'Última actualización',latestNews:'Últimas noticias',source:'Fuente',read:'Leer fuente ↗',noNews:'No hay noticias recientes relacionadas en la edición actual del Radar.',learnLab:'Laboratorio de IA',learnLabText:'Organización que investiga y desarrolla tecnologías o modelos de inteligencia artificial.',learnModel:'Modelo',learnModelText:'Sistema de inteligencia artificial sobre el cual pueden construirse diferentes productos.',learnProduct:'Producto',learnProductText:'Servicio que permite utilizar las capacidades de uno o varios modelos.',learnApp:'Aplicación con IA',learnAppText:'Software que utiliza modelos propios o de terceros para resolver funciones concretas.'},
 en:{ecosystems:'AI laboratories and ecosystems',ecosystemsIntro:'We first show organizations that research, train models, or maintain relevant AI ecosystems of their own. Models, products, and applications built on that technology are separated afterwards.',allRegions:'Worldwide',open:'Open ↗',analysis:'View profile',general:'General-purpose assistant comparison',generalIntro:'An indicative comparison of general products. There is no single universal ranking: also review strengths by specialty.',apps:'AI-powered applications',appsIntro:'Useful products that add value through design, productivity, coding, content, or automation. They are shown separately when they rely mainly on third-party models.',learn:'Understand the ecosystem without unnecessary complexity',searchHint:'Try: “I want to make a video”, “I need to code” or “I want to research”.',results:'results',official:'Official site',save:'Save',saved:'Saved',discard:'Dismiss',what:'What it is',developer:'Developer',origin:'Country of origin',capabilities:'What it can do',strength:'Where it stands out',models:'Models or technology',research:'Own research',ownModels:'Own models',products:'Ecosystem / products',useful:'Who it is useful for',examples:'Example uses',availability:'Availability',pricing:'Plans',updated:'Last updated',latestNews:'Latest news',source:'Source',read:'Read source ↗',noNews:'No related recent news is available in the current Radar edition.',learnLab:'AI laboratory',learnLabText:'An organization that researches and develops artificial intelligence technologies or models.',learnModel:'Model',learnModelText:'An AI system on top of which different products can be built.',learnProduct:'Product',learnProductText:'A service that gives users access to capabilities from one or more models.',learnApp:'AI-powered application',learnAppText:'Software that uses its own or third-party models to perform specific tasks.'},
 fil:{ecosystems:'Mga laboratoryo at ecosystem ng AI',ecosystemsIntro:'Una naming ipinapakita ang mga organisasyong nagsasaliksik, nagsasanay ng mga modelo, o may mahalagang sariling AI ecosystem. Pagkatapos ay malinaw na inihihiwalay ang mga modelo, produkto, at application na nakapatong sa teknolohiyang iyon.',allRegions:'Buong mundo',open:'Buksan ↗',analysis:'Tingnan ang profile',general:'Paghahambing ng mga general-purpose assistant',generalIntro:'Gabay na paghahambing ito, hindi isang absolutong ranking. Tingnan din ang lakas ng bawat sistema ayon sa specialty.',apps:'Mga application na may AI',appsIntro:'Mga kapaki-pakinabang na produktong gumagamit ng AI para sa design, productivity, coding, content, at automation. Hiwalay ang mga pangunahing umaasa sa third-party models.',learn:'Unawain ang AI ecosystem nang simple',searchHint:'Subukan: “gusto kong gumawa ng video”, “kailangan kong mag-code” o “gusto kong magsaliksik”.',results:'resulta',official:'Opisyal na site',save:'I-save',saved:'Naka-save',discard:'Alisin',what:'Ano ito',developer:'Gumagawa',origin:'Bansang pinagmulan',capabilities:'Ano ang kaya nito',strength:'Saan ito mahusay',models:'Mga modelo o teknolohiya',research:'Sariling pananaliksik',ownModels:'Sariling mga modelo',products:'Ecosystem / mga produkto',useful:'Para kanino ito kapaki-pakinabang',examples:'Mga halimbawa ng gamit',availability:'Availability',pricing:'Mga plano',updated:'Huling update',latestNews:'Pinakabagong balita',source:'Pinagmulan',read:'Basahin ang source ↗',noNews:'Walang kaugnay na bagong balita sa kasalukuyang edisyon ng Radar.',learnLab:'AI laboratoryo',learnLabText:'Organisasyong nagsasaliksik at gumagawa ng mga teknolohiya o modelo ng artificial intelligence.',learnModel:'Modelo',learnModelText:'AI system na maaaring gamiting pundasyon ng iba’t ibang produkto.',learnProduct:'Produkto',learnProductText:'Serbisyong nagbibigay-daan upang gamitin ang kakayahan ng isa o higit pang modelo.',learnApp:'Application na may AI',learnAppText:'Software na gumagamit ng sariling modelo o third-party model para sa partikular na gawain.'}
};
function t(k){return (I18N[currentLang]&&I18N[currentLang][k])||I18N.es[k]||k}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

const LABS=new Set(['OpenAI','Anthropic','Google DeepMind','SpaceXAI / xAI','Meta','Microsoft AI','Amazon Web Services AI','NVIDIA','Cohere','Mistral AI','Aleph Alpha','Black Forest Labs','Stability AI','DeepSeek','Z.ai / Zhipu AI','MiniMax','ByteDance Seed','Sakana AI','Preferred Networks','AI21 Labs','Technology Innovation Institute','G42 / Core42']);
const MODEL_PRODUCTS=new Set(['ChatGPT','Claude','Gemini','Grok','Meta AI','Microsoft Copilot','Le Chat','Qwen','Wan','Baidu ERNIE','Tencent Hunyuan','Dreamina Seedance','Kimi','Huawei Pangu','NAVER HyperCLOVA X','LG EXAONE']);
const SPECIAL_APPS=new Set(['GitHub Copilot','Lovable','Canva AI','Runway','Midjourney','Adobe Firefly','Perplexity','Cursor','Replit','Windsurf','Manus','Poe','Hugging Face','Ideogram','Luma AI','Pika','Suno','Udio','Gamma','Notion AI','Jasper','Grammarly','Character.AI','Synthesia']);
const PRODUCT_MAP={
 'OpenAI':'ChatGPT, Codex, API, GPT, GPT Image, GPT-Live','Anthropic':'Claude, Claude Code, API','Google DeepMind':'Gemini, modelos de voz, visión, ciencia y agentes','SpaceXAI / xAI':'Grok, Grok Build, Grok Bot, Imagine','Meta':'Llama, Meta AI, modelos creativos','Microsoft AI':'Copilot, Azure AI, Microsoft 365 AI','Amazon Web Services AI':'Bedrock, servicios de IA empresarial','NVIDIA':'CUDA, NIM, modelos, robótica y plataformas de inferencia','Cohere':'Command, Embed y plataforma empresarial','Mistral AI':'Le Chat, Studio, Vibe, API y modelos Mistral','DeepSeek':'DeepSeek Chat, API y familia DeepSeek','Z.ai / Zhipu AI':'GLM, Z.ai, ZCode y herramientas agentes','MiniMax':'modelos de lenguaje, audio y video','ByteDance Seed':'Doubao, Seedance y modelos multimodales','Sakana AI':'investigación y modelos experimentales','AI21 Labs':'Jamba y plataforma empresarial','Technology Innovation Institute':'Falcon y proyectos de investigación','G42 / Core42':'infraestructura, plataformas y modelos regionales'};
const OFFICIAL={
 'OpenAI':'https://openai.com/','ChatGPT':'https://chatgpt.com/','Anthropic':'https://www.anthropic.com/','Claude':'https://claude.ai/','Google DeepMind':'https://deepmind.google/','Gemini':'https://gemini.google.com/','SpaceXAI / xAI':'https://x.ai/','Grok':'https://grok.com/','Meta':'https://ai.meta.com/','Meta AI':'https://www.meta.ai/','Microsoft AI':'https://microsoft.ai/','Microsoft Copilot':'https://copilot.microsoft.com/','GitHub Copilot':'https://github.com/features/copilot','Amazon Web Services AI':'https://aws.amazon.com/ai/','NVIDIA':'https://www.nvidia.com/en-us/ai/','Cohere':'https://cohere.com/','Mistral AI':'https://mistral.ai/','Le Chat':'https://chat.mistral.ai/','Aleph Alpha':'https://aleph-alpha.com/','Black Forest Labs':'https://blackforestlabs.ai/','Stability AI':'https://stability.ai/','ElevenLabs':'https://elevenlabs.io/','Synthesia':'https://www.synthesia.io/','Lovable':'https://lovable.dev/','DeepSeek':'https://www.deepseek.com/','Qwen':'https://qwen.ai/','Wan':'https://wan.video/','Baidu ERNIE':'https://yiyan.baidu.com/','Tencent Hunyuan':'https://hunyuan.tencent.com/','ByteDance Seed':'https://seed.bytedance.com/','Dreamina Seedance':'https://dreamina.capcut.com/','Z.ai / Zhipu AI':'https://z.ai/','Kimi':'https://www.kimi.com/','MiniMax':'https://www.minimax.io/','Huawei Pangu':'https://www.huaweicloud.com/intl/en-us/product/pangu.html','NAVER HyperCLOVA X':'https://clova.ai/','LG EXAONE':'https://www.lgresearch.ai/','Sakana AI':'https://sakana.ai/','Preferred Networks':'https://www.preferred.jp/en/','AI21 Labs':'https://www.ai21.com/','Technology Innovation Institute':'https://www.tii.ae/','G42 / Core42':'https://www.g42.ai/','Canva AI':'https://www.canva.com/ai-assistant/','Runway':'https://runwayml.com/','Midjourney':'https://www.midjourney.com/','Adobe Firefly':'https://firefly.adobe.com/','Perplexity':'https://www.perplexity.ai/','Cursor':'https://cursor.com/','Replit':'https://replit.com/','Windsurf':'https://windsurf.com/','Manus':'https://manus.im/','Poe':'https://poe.com/','Hugging Face':'https://huggingface.co/','Ideogram':'https://ideogram.ai/','Luma AI':'https://lumalabs.ai/','Pika':'https://pika.art/','Suno':'https://suno.com/','Udio':'https://www.udio.com/','Gamma':'https://gamma.app/','Notion AI':'https://www.notion.com/product/ai','Jasper':'https://www.jasper.ai/','Grammarly':'https://www.grammarly.com/ai','Character.AI':'https://character.ai/'};
const COMPANY_OFFICIAL={'Google':'https://ai.google/','Alibaba':'https://www.alibabacloud.com/en/solutions/generative-ai','Microsoft':'https://www.microsoft.com/ai/','Moonshot AI':'https://www.moonshot.ai/','ByteDance':'https://seed.bytedance.com/','Zhipu AI':'https://z.ai/','Huawei':'https://www.huawei.com/','NAVER':'https://clova.ai/','LG AI Research':'https://www.lgresearch.ai/','TII':'https://www.tii.ae/','G42':'https://www.g42.ai/'};
function atlasUrl(i){return i.url||OFFICIAL[i.name]||COMPANY_OFFICIAL[i.company]||null}
function logoHtml(i){const u=atlasUrl(i),initials=(i.name||'?').replace(/[^A-Za-z0-9]/g,'').slice(0,2).toUpperCase();if(!u)return `<div class="brandLogo"><span>${esc(initials)}</span></div>`;try{const origin=new URL(u).origin;return `<div class="brandLogo"><img src="${origin}/favicon.ico" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><span style="display:none">${esc(initials)}</span></div>`}catch(e){return `<div class="brandLogo"><span>${esc(initials)}</span></div>`}}
function structure(i){if(SPECIAL_APPS.has(i.name)||i.class==='Aplicación sobre terceros')return 'Aplicación con IA';if(LABS.has(i.name))return 'Laboratorio / ecosistema';if(MODEL_PRODUCTS.has(i.name))return 'Modelo / producto oficial';return i.class==='Modelo propio'?'Desarrollador de modelos':i.class||'Producto de IA'}
function isLab(i){return LABS.has(i.name)}
function isApp(i){return SPECIAL_APPS.has(i.name)||i.class==='Aplicación sobre terceros'}
function ownResearch(i){return isLab(i)?(currentLang==='es'?'Sí, actividad pública de I+D':currentLang==='en'?'Yes, public R&D activity':'Oo, may pampublikong R&D activity'):(currentLang==='es'?'Depende de la organización desarrolladora':currentLang==='en'?'Depends on the developing organization':'Depende sa organisasyong gumagawa')}
function ownModels(i){if(i.class==='Modelo propio')return currentLang==='es'?'Sí / familia propia':currentLang==='en'?'Yes / own model family':'Oo / sariling model family';if(i.class==='Híbrida')return currentLang==='es'?'Mixto':currentLang==='en'?'Mixed':'Halo';return currentLang==='es'?'Principalmente modelos externos':currentLang==='en'?'Mainly third-party models':'Pangunahing third-party models'}
const CAP_EN={'Texto':'Text','Imagen':'Image','Audio':'Audio','Video':'Video','Programación':'Coding','Agentes':'Agents','Investigación':'Research','Ciencia':'Science','Empresa':'Enterprise','Productividad':'Productivity','Modelos':'Models','Robótica':'Robotics','Cómputo':'Compute','Razonamiento':'Reasoning','Diseño':'Design','Voz':'Voice','Open weights':'Open weights','Multimodal':'Multimodal','Industria':'Industry','Web':'Web','Avatares':'Avatars','Recuperación de información':'Retrieval'};
const CAP_FIL={'Texto':'Teksto','Imagen':'Larawan','Audio':'Audio','Video':'Video','Programación':'Coding','Agentes':'Agents','Investigación':'Pananaliksik','Ciencia':'Agham','Empresa':'Enterprise','Productividad':'Productivity','Modelos':'Mga modelo','Robótica':'Robotics','Cómputo':'Compute','Razonamiento':'Reasoning','Diseño':'Design','Voz':'Boses','Open weights':'Open weights','Multimodal':'Multimodal','Industria':'Industriya','Web':'Web','Avatares':'Avatars','Recuperación de información':'Retrieval'};
function capLabel(c){return currentLang==='en'?(CAP_EN[c]||c):currentLang==='fil'?(CAP_FIL[c]||c):c}
function itemSummary(i){if(currentLang==='es')return i.desc||'';const caps=(i.caps||[]).slice(0,5).map(capLabel).join(', ');if(currentLang==='en')return `${i.name} is a ${structure(i).toLowerCase()} developed by ${i.company}. Its main capabilities include ${caps}. It is especially relevant for ${i.best||'AI workflows'}.`;return `${i.name} ay isang ${structure(i).toLowerCase()} na binuo ng ${i.company}. Kabilang sa pangunahing kakayahan nito ang ${caps}. Kapaki-pakinabang ito lalo na para sa ${i.best||'mga gawain gamit ang AI'}.`}
function translatedBest(i){if(currentLang==='es')return i.best||'';const caps=(i.caps||[]).slice(0,3).map(capLabel).join(', ');return currentLang==='en'?`${caps || i.best}`:`${caps || i.best}`}
function productsFor(i){return PRODUCT_MAP[i.name]||(isLab(i)?(currentLang==='es'?'Modelos, API y productos oficiales según el laboratorio':currentLang==='en'?'Models, APIs and official products from the lab':'Mga modelo, API at opisyal na produkto ng laboratoryo'):(currentLang==='es'?'Producto principal mostrado en el Atlas':currentLang==='en'?'Main product shown in the Atlas':'Pangunahing produktong ipinapakita sa Atlas'))}
function examplesFor(i){const caps=(i.caps||[]).slice(0,4).map(capLabel).join(', ');return currentLang==='es'?`Casos relacionados con ${caps||i.best}.`:currentLang==='en'?`Use cases related to ${caps||i.best}.`:`Mga gamit na kaugnay ng ${caps||i.best}.`}
function availabilityFor(){return currentLang==='es'?'Web, aplicación o API según producto y región. Verifica la disponibilidad actual en el sitio oficial.':currentLang==='en'?'Web, app, or API depending on the product and region. Check current availability on the official site.':'Web, app, o API depende sa produkto at rehiyon. Tingnan ang kasalukuyang availability sa opisyal na site.'}
function pricingFor(){return currentLang==='es'?'Los planes y precios cambian con frecuencia; consulta la fuente oficial.':currentLang==='en'?'Plans and pricing change frequently; check the official source.':'Madalas magbago ang mga plano at presyo; tingnan ang opisyal na source.'}

const NEEDS={
 'video':['video','seedance','wan','runway','luma','pika','multimodal'],'hacer un video':['video'],'crear un video':['video'],'make a video':['video'],'gumawa ng video':['video'],
 'programar':['programación','coding','agentes'],'crear una aplicación':['programación','web','agentes'],'crear una app':['programación','web','agentes'],'code':['programación','coding'],'build an app':['programación','web','agentes'],'mag-code':['programación','coding'],
 'investigar':['investigación','texto','agentes'],'research':['investigación','texto','agentes'],'magsaliksik':['investigación','texto','agentes'],
 'imagen':['imagen','diseño'],'crear imágenes':['imagen','diseño'],'create images':['imagen','diseño'],'gumawa ng larawan':['imagen','diseño'],
 'presentación':['productividad','diseño','texto'],'presentation':['productividad','diseño','texto'],'presentasyon':['productividad','diseño','texto'],
 'inglés':['texto','audio','voz'],'english':['texto','audio','voz'],'automation':['agentes','empresa','productividad'],'automatizar':['agentes','empresa','productividad'],'negocio':['empresa','productividad','agentes']
};
function normalized(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function queryTokens(q){const nq=normalized(q);let terms=[nq];Object.entries(NEEDS).forEach(([k,v])=>{if(nq.includes(normalized(k)))terms.push(...v.map(normalized))});return [...new Set(terms.filter(Boolean))]}
function matchesQuery(i,q){if(!q)return true;const hay=normalized(JSON.stringify(i));return queryTokens(q).some(term=>hay.includes(term))}

function cardActions(i){const idx=directory.indexOf(i),u=atlasUrl(i);return `<div class="cardActionRow">${u?`<a class="visitBtn" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${t('open')}</a>`:''}<button class="secondaryBtn" onclick="openDirectory(directory[${idx}])">${t('analysis')}</button>${typeof quickFavorite==='function'?quickFavorite(i):''}</div>`}
function renderEcoCard(i){return `<article class="ecoCard"><div class="ecoHead">${logoHtml(i)}<span class="ecoType">${esc(structure(i))}</span></div><h3>${esc(i.name)}</h3><div class="ecoMeta">${esc(i.company)} · ${esc(i.country)}</div><p>${esc(itemSummary(i))}</p><div class="capLine"><strong>${t('capabilities')}:</strong> ${(i.caps||[]).slice(0,6).map(capLabel).map(esc).join(' · ')}</div>${cardActions(i)}</article>`}
function renderAppCard(i){return `<article class="appCard"><div class="appHead">${logoHtml(i)}<span class="appType">${esc(structure(i))}</span></div><h3>${esc(i.name)}</h3><div class="appMeta">${esc(i.company)} · ${esc(i.country)}</div><p>${esc(itemSummary(i))}</p><div class="capLine"><strong>${t('strength')}:</strong> ${esc(translatedBest(i))}</div>${cardActions(i)}</article>`}

function renderEcosystems(){const box=document.querySelector('#ecosystemGrid');if(!box)return;const rows=directory.filter(isLab).filter(i=>!activeEcoRegion||i.region===activeEcoRegion);box.innerHTML=rows.map(renderEcoCard).join('');const pills=document.querySelector('#ecosystemRegions');if(pills){const regions=[...new Set(directory.filter(isLab).map(i=>i.region))].sort();pills.innerHTML=`<button class="regionPill ${!activeEcoRegion?'active':''}" data-r="">${t('allRegions')}</button>`+regions.map(r=>`<button class="regionPill ${activeEcoRegion===r?'active':''}" data-r="${esc(r)}">${esc(r)}</button>`).join('');pills.querySelectorAll('.regionPill').forEach(b=>b.onclick=()=>{activeEcoRegion=b.dataset.r;renderEcosystems()})}}
function renderApplications(){const box=document.querySelector('#applicationsGrid');if(!box)return;const rows=directory.filter(isApp);box.innerHTML=rows.map(renderAppCard).join('')}

function renderDirectoryV2(){const search=document.querySelector('#search'),classFilter=document.querySelector('#classFilter'),regionFilter=document.querySelector('#regionFilter'),capFilter=document.querySelector('#capFilter'),sortFilter=document.querySelector('#sortFilter');if(!search||!document.querySelector('#directoryGrid'))return;let rows=directory.filter(i=>matchesQuery(i,search.value)&&(!classFilter.value||i.class===classFilter.value)&&(!regionFilter.value||i.region===regionFilter.value)&&(!capFilter.value||i.caps.includes(capFilter.value)));const p={'Modelo propio':0,'Híbrida':1,'Aplicación sobre terceros':2};if(sortFilter.value==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));else if(sortFilter.value==='country')rows.sort((a,b)=>a.country.localeCompare(b.country)||a.name.localeCompare(b.name));else rows.sort((a,b)=>(isLab(b)-isLab(a))||(p[a.class]-p[b.class])||a.name.localeCompare(b.name));const count=document.querySelector('#resultCount');if(count)count.textContent=`${rows.length} ${t('results')}`;document.querySelector('#directoryGrid').innerHTML=rows.length?rows.map(i=>{const idx=directory.indexOf(i),u=atlasUrl(i);return `<article class="card ${typeof isFavorite==='function'&&isFavorite(i)?'isFavorite':''} ${typeof isDisliked==='function'&&isDisliked(i)?'isDisliked':''}"><div class="cardTop"><div class="dirIdentity">${logoHtml(i)}<div class="dirIdentityText"><h3>${esc(i.name)}</h3><div class="sub">${esc(i.company)}</div><span class="structureBadge">${esc(structure(i))}</span></div></div><span class="type">${esc(i.class)}</span></div><p class="desc">${esc(itemSummary(i))}</p><p class="best"><strong>${t('strength')}:</strong> ${esc(translatedBest(i))}</p><div class="tags">${(i.caps||[]).slice(0,6).map(c=>`<span class="tag">${esc(capLabel(c))}</span>`).join('')}</div>${typeof prefControls==='function'?prefControls(i):''}<div class="cardFooter"><span class="country">${esc(i.country)}</span><div class="cardLinks">${u?`<a class="visitBtn" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${t('open')}</a>`:''}<button class="details" onclick="openDirectory(directory[${idx}])">${t('analysis')} →</button></div></div></article>`}).join(''):`<div class="empty">0 ${t('results')}. ${t('searchHint')}</div>`}

function relatedNews(i){const keys=[i.name,i.company].map(normalized);return radarData.filter(n=>{const rel=normalized((n.company||'')+' '+(n.related||'')+' '+(n.title||''));return keys.some(k=>k&&rel.includes(k))}).slice(0,3)}
function richFact(label,value){return `<div class="richFact"><b>${esc(label)}</b><span>${esc(value||'—')}</span></div>`}
function openDirectoryV2(i){if(!i)return;const u=atlasUrl(i),news=relatedNews(i);modalContent.innerHTML=`<div class="label">${esc(structure(i))}</div><h2>${esc(i.name)}</h2><div class="company">${esc(i.company)} · ${esc(i.country)}</div><div class="modalActions">${u?`<a class="visitBtn" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${t('official')} ↗</a>`:''}</div>${typeof prefControls==='function'?prefControls(i):''}<div class="detailBlock"><h4>${t('what')}</h4><p>${esc(itemSummary(i))}</p></div><div class="detailBlock"><div class="richGrid">${richFact(t('developer'),i.company)}${richFact(t('origin'),i.country)}${richFact(t('strength'),translatedBest(i))}${richFact(t('models'),i.model)}${richFact(t('research'),ownResearch(i))}${richFact(t('ownModels'),ownModels(i))}${richFact(t('products'),productsFor(i))}${richFact(t('useful'),translatedBest(i))}${richFact(t('examples'),examplesFor(i))}${richFact(t('availability'),availabilityFor())}${richFact(t('pricing'),pricingFor())}${richFact(t('updated'),'2026-09-16')}</div></div><div class="detailBlock"><h4>${t('capabilities')}</h4><div class="tags">${(i.caps||[]).map(c=>`<span class="tag">${esc(capLabel(c))}</span>`).join('')}</div></div><div class="detailBlock"><h4>${t('latestNews')}</h4><div class="latestNewsBlock">${news.length?news.map(n=>`<a class="latestNewsLink" href="${esc(n.url)}" target="_blank" rel="noopener noreferrer"><b>${esc(n.title)}</b><span>${esc(n.date||'')} · ${esc(n.source||'')}</span></a>`).join(''):`<div class="newsEmpty">${t('noNews')}</div>`}</div></div>`;modal.classList.add('show');document.body.style.overflow='hidden'}

function renderNewsV2(){const b=document.querySelector('#newsDrawerList');if(!b)return;if(!radarData.length){b.innerHTML=`<div class="newsEmpty">${t('noNews')}</div>`;return}b.innerHTML=radarData.slice(0,10).map((n,i)=>`<article class="newsItem"><div class="newsNum">${String(i+1).padStart(2,'0')}</div><div><span class="${n.official?'newsSourceOfficial':''}">${esc(n.source||'Fuente')}</span><h3>${esc(n.title)}</h3><div class="newsInfo">${n.company?`<em class="newsTag">${esc(n.company)}</em>`:''}${n.region?`<em class="newsTag">${esc(n.region)}</em>`:''}${n.category?`<em class="newsTag">${esc(n.category)}</em>`:''}<time>${esc(n.date||'')}</time></div><p>${esc(n.summary||'')}</p><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">${t('read')}</a></div></article>`).join('')}
async function loadRadar(){try{const r=await fetch(`data/news.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('news');const j=await r.json();radarData=Array.isArray(j)?j:(j.items||[])}catch(e){if(typeof aiNews!=='undefined')radarData=aiNews.map(n=>({title:n[0],source:n[1],summary:n[2],url:n[3],date:'2026-09-16',category:'IA'}))}renderNewsV2()}

function renderTaxonomy(){const el=document.querySelector('#taxonomyGrid');if(!el)return;el.innerHTML=[[t('learnLab'),t('learnLabText')],[t('learnModel'),t('learnModelText')],[t('learnProduct'),t('learnProductText')],[t('learnApp'),t('learnAppText')]].map((x,i)=>`<article class="taxCard"><span class="taxNo">0${i+1}</span><b>${esc(x[0])}</b><p>${esc(x[1])}</p></article>`).join('')}
function applyTranslations(){document.documentElement.lang=currentLang==='fil'?'fil':currentLang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(t(k))el.textContent=t(k)});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{el.placeholder=t(el.dataset.i18nPlaceholder)});document.querySelectorAll('.langBtn').forEach(b=>b.classList.toggle('active',b.dataset.lang===currentLang));renderEcosystems();renderApplications();renderTaxonomy();renderDirectoryV2();renderNewsV2()}
function setLanguage(lang){if(!I18N[lang])return;currentLang=lang;localStorage.setItem(LANG_KEY,lang);applyTranslations()}

function init(){
 document.querySelectorAll('.langBtn').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
 if(typeof openDirectory==='function'){window.openDirectory=openDirectoryV2;try{openDirectory=openDirectoryV2}catch(e){}}
 if(typeof renderDirectory==='function'){window.renderDirectory=renderDirectoryV2;try{renderDirectory=renderDirectoryV2}catch(e){}}
 if(typeof renderNews==='function'){window.renderNews=renderNewsV2;try{renderNews=renderNewsV2}catch(e){}}
 ['search','classFilter','regionFilter','capFilter','sortFilter'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(id==='search'?'input':'change',()=>setTimeout(renderDirectoryV2,0))});
 const clear=document.querySelector('#clearFilters');if(clear)clear.addEventListener('click',()=>setTimeout(renderDirectoryV2,0));
 applyTranslations();loadRadar();
}
init();
})();
