/* AI World Atlas — Comunidad v3: chat estable, debates, menciones, avatares y una imagen/GIF. */
(function(){
const cfg=window.ATLAS_BACKEND;if(!cfg?.url||!cfg?.key||!window.supabase)return;
const db=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const K={visitor:'aiWorldAtlasVisitorIdV1',liked:'aiWorldAtlasLikedV1',profile:'aiWorldAtlasChatProfileV2',reminder:'aiWorldAtlasCommunityReminderV1'};
let visitor=localStorage.getItem(K.visitor);if(!visitor){visitor=crypto.randomUUID();localStorage.setItem(K.visitor,visitor)}
let profile=readProfile(),gender=profile?.gender||'',tab='chat',view='list',topicId=null,poll=null,selectedFile=null;
const BOYS=['CapitánPrompt','DonByte','Señor404','PandaProgramador','TíoTensor','CaféConCódigo','RobotConSueño','PixelPirata','ComandanteCache','LoboLinux','MagoDelPrompt','ByteBandido','CerebroTurbo','GatoGPT','CosmoCoder','DoctorBug','DonAlgoritmo','NeuronaNinja'];
const GIRLS=['ReinaDelPrompt','LunaBinaria','ChicaQuantum','PixelPrincesa','DamaDelDato','GataGPT','AdaCósmica','ByteSirena','RobotConTacones','MusaDigital','CapitanaCloud','CaféYCódigo','NovaNeurona','EstrellaTensor','PandaPixel','DoñaDebug','NeuronaNinja','DivaDigital'];
const EMOJIS=['😀','😂','😍','🤩','😎','🤖','👋','🔥','✨','❤️','👍','👏','🚀','🌎','💡','🧠','🎉','🤔','👀','💻'];
function q(s){return document.querySelector(s)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function rich(v){return String(v??'').split(/(@[\p{L}\p{N}_-]{2,24})/gu).map(p=>p.startsWith('@')?`<span class="mention">${esc(p)}</span>`:esc(p)).join('')}
function readProfile(){try{const p=JSON.parse(localStorage.getItem(K.profile)||'null');return p&&['boy','girl'].includes(p.gender)&&p.alias?{gender:p.gender,alias:String(p.alias).slice(0,24)}:null}catch{return null}}
function saveProfile(p){profile=p;gender=p.gender;localStorage.setItem(K.profile,JSON.stringify(p))}
function randomAlias(){const a=gender==='girl'?GIRLS:BOYS;return a[Math.floor(Math.random()*a.length)]}
function who(g){return g==='girl'?'Chica':'Chico'}
function handle(alias){const h=String(alias||'usuario').normalize('NFKC').replace(/[^\p{L}\p{N}_-]/gu,'').slice(0,24);return '@'+(h||'usuario')}
function avatarUrl(alias,g){const seed=encodeURIComponent(`${g||'anon'}-${alias||'visitante'}`);return `https://api.dicebear.com/10.x/avataaars/svg?seed=${seed}`}
function avatar(alias,g,cls=''){return `<span class="genderAvatar avatarPic ${esc(g||'anon')} ${cls}"><img src="${avatarUrl(alias,g)}" alt="Avatar de ${esc(alias||'usuario')}" loading="lazy" referrerpolicy="no-referrer"></span>`}
function when(v){try{return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return ''}}
function media(url){return url?`<button class="mediaOpen" data-media="${esc(url)}" aria-label="Ampliar imagen"><img src="${esc(url)}" alt="Imagen compartida" loading="lazy"></button>`:''}
async function call(action,extra={}){const {data,error}=await db.functions.invoke('atlas-community',{body:{action,...extra}});if(error)throw error;if(data?.error){const e=new Error(data.error);e.code=data.error;throw e}return data||{}}
async function uploadMedia(file){if(!file)return null;if(file.size>1048576)throw Object.assign(new Error('media_too_large'),{code:'media_too_large'});if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw Object.assign(new Error('invalid_media'),{code:'invalid_media'});const ticket=await call('media_ticket',{visitor_id:visitor,mime:file.type,size:file.size});const {error}=await db.storage.from('community-media').uploadToSignedUrl(ticket.path,ticket.token,file,{contentType:file.type});if(error)throw error;return ticket.public_url}
function shell(){document.body.insertAdjacentHTML('beforeend',`
<button class="communityFab" id="communityFab"><i></i><span>💬 Comunidad</span><b id="fabOnline">…</b></button>
<div class="communityShade" id="communityShade"></div>
<aside class="communityDrawer" id="communityDrawer" aria-hidden="true">
 <header class="communityHead"><div class="communityHeadIcon">🌎</div><div><small>AI WORLD ATLAS</small><h2>Comunidad en vivo</h2><p><i></i> Personas hablando de inteligencia artificial</p></div><div class="communityHeadActions"><button id="communityExpand" title="Ampliar">⛶</button><button id="communityClose" title="Cerrar">×</button></div></header>
 <div class="communityStats"><button><b id="sVisitors">—</b><span>👁 Visitantes</span></button><button><b id="sOnline">—</b><span>🟢 En vivo</span></button><button id="likeCommunity"><b id="sLikes">—</b><span>♥ Me gusta</span></button><button><b id="sTopics">—</b><span>🧠 Debates</span></button></div>
 <div id="profileBox"></div>
 <nav class="communityTabs"><button data-tab="chat" class="active">💬 Chat en vivo</button><button data-tab="forum">🧠 Debates IA</button></nav>
 <div class="communityTools"><button id="socialRefresh" title="Actualizar">↻</button><button id="socialUp" title="Subir">↑</button><button id="socialDown" title="Bajar">↓</button><span>Usa <b>@apodo</b> para mencionar</span></div>
 <main class="communityBody" id="communityBody"></main>
 <footer class="communityFoot">🔒 Sin cuenta · 1 imagen/GIF máximo · 1 MB · <button id="communityLikeFoot">♥ ¿Te gusta el Atlas?</button></footer>
</aside>
<div class="mediaLightbox" id="mediaLightbox"><button id="mediaClose">×</button><img id="mediaFull" alt="Imagen ampliada"></div>
<div class="atlasNudge" id="atlasNudge"><button id="nudgeClose">×</button><strong>¿Te está gustando AI World Atlas? ❤️</strong><p>Déjanos un me gusta o entra a Debates IA y cuéntanos qué mejorarías.</p><div><button id="nudgeLike">♥ Me gusta</button><button id="nudgeDebate">🧠 Dejar comentario</button></div></div>`);
q('#communityFab').onclick=open;q('#communityShade').onclick=close;q('#communityClose').onclick=close;q('#communityExpand').onclick=()=>q('#communityDrawer').classList.toggle('expanded');q('#likeCommunity').onclick=like;q('#communityLikeFoot').onclick=like;q('#socialRefresh').onclick=manualRefresh;q('#socialUp').onclick=()=>scrollSocial('up');q('#socialDown').onclick=()=>scrollSocial('down');q('#mediaClose').onclick=closeMedia;q('#mediaLightbox').onclick=e=>{if(e.target===q('#mediaLightbox'))closeMedia()};document.querySelectorAll('.communityTabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));renderProfile();stats();switchTab('chat');setInterval(stats,30000);maybeNudge();
}
function open(){q('#communityDrawer').classList.add('show');q('#communityShade').classList.add('show');q('#communityDrawer').setAttribute('aria-hidden','false');manualRefresh();if(!poll)poll=setInterval(autoRefresh,6000)}
function close(){q('#communityDrawer').classList.remove('show');q('#communityShade').classList.remove('show');q('#communityDrawer').setAttribute('aria-hidden','true')}
function autoRefresh(){if(!q('#communityDrawer')?.classList.contains('show'))return;const body=q('#communityBody');if(body?.contains(document.activeElement))return;if(tab==='chat'){const input=q('#chatInput');if(input&&(input.value.trim()||selectedFile))return;loadChat(true)}else if(view==='list')loadTopics(true)}
function manualRefresh(){if(tab==='chat')loadChat();else if(view==='topic'&&topicId)openTopic(topicId);else loadTopics()}
function scrollSocial(dir){const pane=q('.chatStream')||q('#communityBody');if(!pane)return;pane.scrollTo({top:dir==='up'?0:pane.scrollHeight,behavior:'smooth'})}
function openMedia(url){q('#mediaFull').src=url;q('#mediaLightbox').classList.add('show')}
function closeMedia(){q('#mediaLightbox').classList.remove('show');q('#mediaFull').removeAttribute('src')}
function wireMedia(){document.querySelectorAll('[data-media]').forEach(b=>b.onclick=()=>openMedia(b.dataset.media))}
function renderProfile(){const box=q('#profileBox');if(profile){box.innerHTML=`<div class="communityIdentity">${avatar(profile.alias,profile.gender)}<div><small>${who(profile.gender)} · identidad anónima</small><strong>${esc(profile.alias)}</strong><em>${esc(handle(profile.alias))}</em></div><button id="changeProfile">Cambiar</button></div>`;q('#changeProfile').onclick=()=>{profile=null;gender='';localStorage.removeItem(K.profile);renderProfile();switchTab(tab)};return}
box.innerHTML=`<div class="communityJoin"><div><strong>👋 Entra con una identidad divertida</strong><p>Cada apodo recibe un avatar diferente. No pedimos correo ni cuenta.</p></div><div class="genderPicker"><button data-g="boy" class="${gender==='boy'?'on boy':''}">👨 Soy chico</button><button data-g="girl" class="${gender==='girl'?'on girl':''}">👩 Soy chica</button></div><div class="aliasPicker"><input id="aliasInput" maxlength="24" placeholder="Tu apodo (opcional)"><button id="randomAlias">🎲 Sorpréndeme</button></div><button class="joinNow" id="joinNow">Entrar anónimo →</button><span id="joinError"></span></div>`;box.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{gender=b.dataset.g;renderProfile()});q('#randomAlias').onclick=()=>{q('#aliasInput').value=randomAlias()};q('#joinNow').onclick=()=>{if(!gender){q('#joinError').textContent='Primero elige chico o chica.';return}saveProfile({gender,alias:(q('#aliasInput').value.trim()||randomAlias()).slice(0,24)});renderProfile();switchTab(tab)}}
async function stats(){try{const d=await call('stats');q('#sVisitors').textContent=Number(d.visitors_total||0).toLocaleString();q('#sOnline').textContent=Number(d.visitors_online||0).toLocaleString();q('#sLikes').textContent=Number(d.likes_total||0).toLocaleString();q('#sTopics').textContent=Number(d.topics_total||0).toLocaleString();q('#fabOnline').textContent=`${d.visitors_online||0} en vivo`;q('#likeCommunity').classList.toggle('liked',localStorage.getItem(K.liked)==='1')}catch{}}
async function like(){if(localStorage.getItem(K.liked)==='1')return;try{await call('like',{visitor_id:visitor});localStorage.setItem(K.liked,'1');stats()}catch{}}
function switchTab(next){tab=next;view='list';topicId=null;selectedFile=null;document.querySelectorAll('.communityTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));tab==='chat'?loadChat():loadTopics()}
function mediaPicker(prefix){return `<div class="mediaPicker"><label for="${prefix}File">🖼️ Imagen/GIF</label><input id="${prefix}File" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><span id="${prefix}FileName">1 archivo máximo · 1 MB</span></div>`}
function wireFile(prefix){const input=q(`#${prefix}File`),name=q(`#${prefix}FileName`);if(!input)return;input.onchange=()=>{const file=input.files?.[0]||null;if(file&&file.size>1048576){input.value='';selectedFile=null;name.textContent='Máximo 1 MB';name.classList.add('error');return}selectedFile=file;name.classList.remove('error');name.textContent=file?`✓ ${file.name}`:'1 archivo máximo · 1 MB'}}
async function loadChat(silent=false){const body=q('#communityBody');if(!silent)body.innerHTML='<div class="communityLoading">Cargando conversación…</div>';try{const d=await call('messages');const rows=(d.messages||[]).slice().reverse();body.innerHTML=`<section class="chatStream">${rows.length?rows.map(m=>`<article class="msg">${avatar(m.alias,m.gender)}<div><header><b>${esc(m.alias)}</b><em>${who(m.gender)}</em><time>${esc(when(m.created_at))}</time></header><p>${rich(m.message)}</p>${media(m.media_url)}<div class="socialMiniActions"><button data-mention="${esc(m.alias)}">↩ ${esc(handle(m.alias))}</button><button class="reportBtn" data-report="chat" data-id="${m.id}">⚑</button></div></div></article>`).join(''):'<div class="emptySocial">💬 Aún no hay mensajes. Inicia la conversación.</div>'}</section>${chatComposer()}`;wireReports();wireMedia();wireMentions('#chatInput');wireChat();if(!silent)q('.chatStream')?.scrollTo({top:q('.chatStream').scrollHeight})}catch{if(!silent)body.innerHTML='<div class="emptySocial">No fue posible cargar el chat.</div>'}}
function chatComposer(){if(!profile)return '<button class="lockedSocial" id="lockedSocial">🔒 Elige tu identidad arriba para participar</button>';return `<div class="emojiLine">${EMOJIS.map(e=>`<button type="button" data-e="${e}">${e}</button>`).join('')}</div>${mediaPicker('chat')}<form class="socialComposer" id="chatForm"><textarea id="chatInput" maxlength="500" rows="2" placeholder="Escribe algo… también puedes usar @apodo"></textarea><div><span id="chatCount">0 / 500</span><button>Enviar ➤</button></div></form>`}
function wireChat(){q('#lockedSocial')?.addEventListener('click',()=>q('#profileBox').scrollIntoView({behavior:'smooth'}));const input=q('#chatInput');if(!input)return;wireFile('chat');input.oninput=()=>q('#chatCount').textContent=`${input.value.length} / 500`;document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{input.value=(input.value+b.dataset.e).slice(0,500);input.oninput();input.focus()});q('#chatForm').onsubmit=async e=>{e.preventDefault();const message=input.value.trim();if(!message&&!selectedFile)return;const btn=q('#chatForm button');btn.disabled=true;try{const media_url=await uploadMedia(selectedFile);await call('send',{visitor_id:visitor,alias:profile.alias,gender:profile.gender,message,media_url});selectedFile=null;await loadChat();q('.chatStream')?.scrollTo({top:q('.chatStream').scrollHeight})}catch(err){alert(err.code==='media_too_large'?'La imagen supera 1 MB.':err.code==='unsafe_content'?'Ese texto fue bloqueado por seguridad.':'No se pudo enviar todavía.')}finally{btn.disabled=false}}}
async function loadTopics(silent=false){view='list';const body=q('#communityBody');if(!silent)body.innerHTML='<div class="communityLoading">Cargando debates…</div>';try{const d=await call('topics');body.innerHTML=`<div class="forumIntro"><div><strong>🧠 Debates IA</strong><p>Abre un tema, responde con @apodo y comparte una imagen o GIF.</p></div>${profile?'<button id="newTopic">+ Nuevo tema</button>':''}</div><div class="topicList">${(d.topics||[]).length?(d.topics||[]).map(x=>`<button class="topicCard" data-topic="${x.id}">${avatar(x.alias,x.gender)}<div><small>${esc(x.alias)} · ${who(x.gender)}</small><strong>${esc(x.title)}</strong><p>${rich(x.body)}</p>${x.media_url?'<em>🖼️ Incluye imagen/GIF</em>':''}<em>💬 ${x.reply_count||0} respuestas · ${esc(when(x.created_at))}</em></div></button>`).join(''):'<div class="emptySocial">🧠 No hay debates todavía. Crea el primero.</div>'}</div>${!profile?'<button class="lockedSocial" id="lockedSocial">🔒 Elige tu identidad arriba para abrir un debate</button>':''}`;q('#newTopic')?.addEventListener('click',newTopic);q('#lockedSocial')?.addEventListener('click',()=>q('#profileBox').scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>openTopic(Number(b.dataset.topic)))}catch{if(!silent)body.innerHTML='<div class="emptySocial">No fue posible cargar los debates.</div>'}}
function newTopic(prefill=''){view='new';selectedFile=null;q('#communityBody').innerHTML=`<button class="backTopics" id="backTopics">← Volver</button><form class="topicForm" id="topicForm"><h3>Nuevo debate</h3><p class="formHint">Puedes mencionar a alguien escribiendo <b>@apodo</b>.</p><label>Título <span id="titleCount">0 / 100</span></label><input id="topicTitle" minlength="4" maxlength="100" required placeholder="Ej: ¿Qué IA te sorprendió este año?"><label>Tu idea <span id="bodyCount">0 / 600</span></label><textarea id="topicBody" maxlength="600" rows="6" placeholder="Explica tu punto de vista…">${esc(prefill)}</textarea>${mediaPicker('topic')}<button>Publicar debate →</button></form>`;q('#backTopics').onclick=()=>loadTopics();wireFile('topic');['topicTitle','topicBody'].forEach(id=>q('#'+id).oninput=()=>q(id==='topicTitle'?'#titleCount':'#bodyCount').textContent=`${q('#'+id).value.length} / ${id==='topicTitle'?100:600}`);q('#topicBody').oninput();q('#topicForm').onsubmit=async e=>{e.preventDefault();const btn=q('#topicForm>button');btn.disabled=true;try{const media_url=await uploadMedia(selectedFile);const d=await call('create_topic',{visitor_id:visitor,alias:profile.alias,gender:profile.gender,title:q('#topicTitle').value,body:q('#topicBody').value,media_url});selectedFile=null;openTopic(d.topic.id)}catch(err){alert(err.code==='media_too_large'?'La imagen supera 1 MB.':err.code==='unsafe_content'?'El contenido fue bloqueado por seguridad.':'No se pudo publicar.')}finally{btn.disabled=false}}}
async function openTopic(id){view='topic';topicId=id;selectedFile=null;q('#communityBody').innerHTML='<div class="communityLoading">Abriendo debate…</div>';try{const d=await call('topic_replies',{topic_id:id});q('#communityBody').innerHTML=`<div class="topicToolbar"><button class="backTopics" id="backTopics">← Debates</button><button id="refreshTopic">↻ Actualizar</button></div><article class="topicOpen"><header>${avatar(d.topic.alias,d.topic.gender)}<div><small>${esc(d.topic.alias)} · ${who(d.topic.gender)} · ${esc(handle(d.topic.alias))}</small><h3>${esc(d.topic.title)}</h3><time>${esc(when(d.topic.created_at))}</time></div></header><p>${rich(d.topic.body)}</p>${media(d.topic.media_url)}<div class="socialMiniActions"><button data-mention="${esc(d.topic.alias)}">↩ Responder ${esc(handle(d.topic.alias))}</button><button class="reportText" data-report="topic" data-id="${d.topic.id}">⚑ Reportar</button></div></article><div class="replyList">${(d.replies||[]).map(r=>`<article class="reply">${avatar(r.alias,r.gender)}<div><b>${esc(r.alias)}</b><small>${who(r.gender)} · ${esc(when(r.created_at))}</small><p>${rich(r.message)}</p>${media(r.media_url)}<div class="socialMiniActions"><button data-mention="${esc(r.alias)}">↩ ${esc(handle(r.alias))}</button><button class="reportBtn" data-report="reply" data-id="${r.id}">⚑</button></div></div></article>`).join('')}</div>${profile?`${mediaPicker('reply')}<form class="replyForm" id="replyForm"><textarea id="replyInput" maxlength="400" rows="3" placeholder="Responde… usa @apodo si quieres mencionar a alguien"></textarea><div><span id="replyCount">0 / 400</span><button>Responder</button></div></form>`:'<button class="lockedSocial" id="lockedSocial">🔒 Elige tu identidad para responder</button>'}`;q('#backTopics').onclick=()=>loadTopics();q('#refreshTopic').onclick=()=>openTopic(id);wireReports();wireMedia();wireMentions('#replyInput');wireFile('reply');const inp=q('#replyInput');if(inp){inp.oninput=()=>q('#replyCount').textContent=`${inp.value.length} / 400`;q('#replyForm').onsubmit=async e=>{e.preventDefault();if(!inp.value.trim()&&!selectedFile)return;const btn=q('#replyForm button');btn.disabled=true;try{const media_url=await uploadMedia(selectedFile);await call('reply',{visitor_id:visitor,topic_id:id,alias:profile.alias,gender:profile.gender,message:inp.value,media_url});selectedFile=null;await openTopic(id);q('#communityBody').scrollTo({top:q('#communityBody').scrollHeight,behavior:'smooth'})}catch(err){alert(err.code==='media_too_large'?'La imagen supera 1 MB.':err.code==='unsafe_content'?'Ese contenido fue bloqueado por seguridad.':'No se pudo responder todavía.')}finally{btn.disabled=false}}}}catch{loadTopics()}}
function wireMentions(selector){document.querySelectorAll('[data-mention]').forEach(b=>b.onclick=e=>{e.stopPropagation();const input=q(selector);if(!input)return;const text=handle(b.dataset.mention)+' ';if(!input.value.includes(text))input.value=(text+input.value).slice(0,input.maxLength||600);input.dispatchEvent(new Event('input'));input.focus()})}
function wireReports(){document.querySelectorAll('[data-report]').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(!confirm('¿Reportar este contenido para revisión?'))return;try{await call('report',{visitor_id:visitor,content_type:b.dataset.report,content_id:Number(b.dataset.id),reason:'Reporte comunitario'});b.textContent='✓ Reportado';b.disabled=true}catch{}})}
function maybeNudge(){const last=Number(localStorage.getItem(K.reminder)||0),day=86400000;if(Date.now()-last<day)return;setTimeout(()=>{const n=q('#atlasNudge');if(!n)return;n.classList.add('show');localStorage.setItem(K.reminder,String(Date.now()));q('#nudgeClose').onclick=()=>n.classList.remove('show');q('#nudgeLike').onclick=()=>{like();n.classList.remove('show')};q('#nudgeDebate').onclick=()=>{n.classList.remove('show');open();switchTab('forum')}},12000)}
try{navigator.serviceWorker?.register('./sw.js')}catch{}
shell();
})();