/* AI World Atlas — Comunidad v2: chat + debates, anónimo, seguro y persistente. */
(function(){
const cfg=window.ATLAS_BACKEND;if(!cfg?.url||!cfg?.key||!window.supabase)return;
const db=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const K={visitor:'aiWorldAtlasVisitorIdV1',liked:'aiWorldAtlasLikedV1',profile:'aiWorldAtlasChatProfileV2',reminder:'aiWorldAtlasCommunityReminderV1'};
let visitor=localStorage.getItem(K.visitor);if(!visitor){visitor=crypto.randomUUID();localStorage.setItem(K.visitor,visitor)}
let profile=readProfile(),gender=profile?.gender||'',tab='chat',topicId=null,poll=null;
const BOYS=['CapitánPrompt','DonByte','Señor404','PandaProgramador','TíoTensor','CaféConCódigo','RobotConSueño','NinjaNeuronal','PixelPirata','ComandanteCache','LoboLinux','MagoDelPrompt','ByteBandido','CerebroTurbo','GatoGPT','CosmoCoder'];
const GIRLS=['ReinaDelPrompt','LunaBinaria','ChicaQuantum','PixelPrincesa','DamaDelDato','NinjaNeuronal','GataGPT','AdaCósmica','ByteSirena','RobotConTacones','MusaDigital','CapitanaCloud','CaféYCódigo','NovaNeurona','EstrellaTensor','PandaPixel'];
const EMOJIS=['😀','😂','😍','🤩','😎','🤖','👋','🔥','✨','❤️','👍','👏','🚀','🌎','💡','🧠','🎉','🤔','👀','💻'];
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function readProfile(){try{const p=JSON.parse(localStorage.getItem(K.profile)||'null');return p&&['boy','girl'].includes(p.gender)&&p.alias?{gender:p.gender,alias:String(p.alias).slice(0,24)}:null}catch{return null}}
function saveProfile(p){profile=p;gender=p.gender;localStorage.setItem(K.profile,JSON.stringify(p))}
function randomAlias(){const a=gender==='girl'?GIRLS:BOYS;return a[Math.floor(Math.random()*a.length)]}
function avatar(g){return g==='girl'?'👩‍🚀':g==='boy'?'👨‍🚀':'🛰️'}
function who(g){return g==='girl'?'Chica':'Chico'}
function when(v){try{return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return ''}}
async function call(action,extra={}){const {data,error}=await db.functions.invoke('atlas-community',{body:{action,...extra}});if(error)throw error;if(data?.error){const e=new Error(data.error);e.code=data.error;throw e}return data||{}}
function shell(){document.body.insertAdjacentHTML('beforeend',`
<button class="communityFab" id="communityFab"><i></i><span>💬 Comunidad</span><b id="fabOnline">…</b></button>
<div class="communityShade" id="communityShade"></div>
<aside class="communityDrawer" id="communityDrawer" aria-hidden="true">
 <header class="communityHead"><div class="communityHeadIcon">🌎</div><div><small>AI WORLD ATLAS</small><h2>Comunidad en vivo</h2><p><i></i> Personas hablando de inteligencia artificial</p></div><button id="communityClose">×</button></header>
 <div class="communityStats"><button><b id="sVisitors">—</b><span>👁 Visitantes</span></button><button><b id="sOnline">—</b><span>🟢 En vivo</span></button><button id="likeCommunity"><b id="sLikes">—</b><span>♥ Me gusta</span></button><button><b id="sTopics">—</b><span>🧠 Debates</span></button></div>
 <div id="profileBox"></div>
 <nav class="communityTabs"><button data-tab="chat" class="active">💬 Chat en vivo</button><button data-tab="forum">🧠 Debates IA</button></nav>
 <main class="communityBody" id="communityBody"></main>
 <footer class="communityFoot">🔒 Sin cuenta · texto tratado como datos, nunca como código · <button id="communityLikeFoot">♥ ¿Te gusta el Atlas?</button></footer>
</aside>
<div class="atlasNudge" id="atlasNudge"><button id="nudgeClose">×</button><strong>¿Te está gustando AI World Atlas? ❤️</strong><p>Déjanos un me gusta o entra a Debates IA y cuéntanos qué mejorarías. Tu opinión ayuda a pulir el Atlas.</p><div><button id="nudgeLike">♥ Me gusta</button><button id="nudgeDebate">🧠 Dejar comentario</button></div></div>`);
q('#communityFab').onclick=open;q('#communityShade').onclick=close;q('#communityClose').onclick=close;q('#likeCommunity').onclick=like;q('#communityLikeFoot').onclick=like;
document.querySelectorAll('.communityTabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));renderProfile();stats();switchTab('chat');setInterval(stats,30000);maybeNudge();
}
function q(s){return document.querySelector(s)}
function open(){q('#communityDrawer').classList.add('show');q('#communityShade').classList.add('show');q('#communityDrawer').setAttribute('aria-hidden','false');switchTab(tab);if(!poll)poll=setInterval(()=>tab==='chat'?loadChat(true):loadTopics(true),6000)}
function close(){q('#communityDrawer').classList.remove('show');q('#communityShade').classList.remove('show');q('#communityDrawer').setAttribute('aria-hidden','true')}
function renderProfile(){const box=q('#profileBox');if(profile){box.innerHTML=`<div class="communityIdentity"><span class="genderAvatar ${profile.gender}">${avatar(profile.gender)}</span><div><small>${who(profile.gender)} · identidad anónima</small><strong>${esc(profile.alias)}</strong></div><button id="changeProfile">Cambiar</button></div>`;q('#changeProfile').onclick=()=>{profile=null;gender='';localStorage.removeItem(K.profile);renderProfile();switchTab(tab)};return}
box.innerHTML=`<div class="communityJoin"><div><strong>👋 Entra con una identidad divertida</strong><p>No pedimos correo ni cuenta. Elige cómo quieres aparecer y un apodo.</p></div><div class="genderPicker"><button data-g="boy" class="${gender==='boy'?'on boy':''}">👨‍🚀 Soy chico</button><button data-g="girl" class="${gender==='girl'?'on girl':''}">👩‍🚀 Soy chica</button></div><div class="aliasPicker"><input id="aliasInput" maxlength="24" placeholder="Tu apodo (opcional)"><button id="randomAlias">🎲 Sorpréndeme</button></div><button class="joinNow" id="joinNow">Entrar anónimo →</button><span id="joinError"></span></div>`;
box.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{gender=b.dataset.g;renderProfile()});q('#randomAlias').onclick=()=>{q('#aliasInput').value=randomAlias()};q('#joinNow').onclick=()=>{if(!gender){q('#joinError').textContent='Primero elige chico o chica.';return}saveProfile({gender,alias:(q('#aliasInput').value.trim()||randomAlias()).slice(0,24)});renderProfile();switchTab(tab)}
}
async function stats(){try{const d=await call('stats');q('#sVisitors').textContent=Number(d.visitors_total||0).toLocaleString();q('#sOnline').textContent=Number(d.visitors_online||0).toLocaleString();q('#sLikes').textContent=Number(d.likes_total||0).toLocaleString();q('#sTopics').textContent=Number(d.topics_total||0).toLocaleString();q('#fabOnline').textContent=`${d.visitors_online||0} en vivo`;q('#likeCommunity').classList.toggle('liked',localStorage.getItem(K.liked)==='1')}catch{}}
async function like(){if(localStorage.getItem(K.liked)==='1')return;try{await call('like',{visitor_id:visitor});localStorage.setItem(K.liked,'1');stats()}catch{}}
function switchTab(next){tab=next;topicId=null;document.querySelectorAll('.communityTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));tab==='chat'?loadChat():loadTopics()}
async function loadChat(silent=false){const body=q('#communityBody');if(!silent)body.innerHTML='<div class="communityLoading">Cargando conversación…</div>';try{const d=await call('messages');const rows=(d.messages||[]).slice().reverse();body.innerHTML=`<section class="chatStream">${rows.length?rows.map(m=>`<article class="msg"><span class="genderAvatar ${esc(m.gender)}">${avatar(m.gender)}</span><div><header><b>${esc(m.alias)}</b><em>${who(m.gender)}</em><time>${esc(when(m.created_at))}</time></header><p>${esc(m.message)}</p><button class="reportBtn" data-report="chat" data-id="${m.id}">⚑</button></div></article>`).join(''):'<div class="emptySocial">💬 Aún no hay mensajes. Inicia la conversación.</div>'}</section>${composer('chat')}`;wireReports();wireChat();if(!silent)q('.chatStream').scrollTop=q('.chatStream').scrollHeight}catch{body.innerHTML='<div class="emptySocial">No fue posible cargar el chat.</div>'}}
function composer(type){if(!profile)return '<button class="lockedSocial" id="lockedSocial">🔒 Elige tu identidad arriba para participar</button>';if(type==='chat')return `<div class="emojiLine">${EMOJIS.map(e=>`<button data-e="${e}">${e}</button>`).join('')}</div><form class="socialComposer" id="chatForm"><textarea id="chatInput" maxlength="500" rows="2" placeholder="Escribe algo sobre IA…"></textarea><div><span id="chatCount">0 / 500</span><button>Enviar ➤</button></div></form>`;return ''}
function wireChat(){q('#lockedSocial')?.addEventListener('click',()=>q('#profileBox').scrollIntoView({behavior:'smooth'}));const input=q('#chatInput');if(!input)return;input.oninput=()=>q('#chatCount').textContent=`${input.value.length} / 500`;document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{input.value=(input.value+b.dataset.e).slice(0,500);input.oninput();input.focus()});q('#chatForm').onsubmit=async e=>{e.preventDefault();const message=input.value.trim();if(!message)return;try{await call('send',{visitor_id:visitor,alias:profile.alias,gender:profile.gender,message});input.value='';await loadChat()}catch(err){alert(err.code==='unsafe_content'?'Ese texto parece contener código ejecutable o un patrón de inyección y fue bloqueado.':'No se pudo enviar todavía. Intenta de nuevo en unos segundos.')}}}
async function loadTopics(silent=false){const body=q('#communityBody');if(!silent)body.innerHTML='<div class="communityLoading">Cargando debates…</div>';try{const d=await call('topics');body.innerHTML=`<div class="forumIntro"><div><strong>🧠 Debates IA</strong><p>Abre un tema, responde ideas y deja propuestas para mejorar el Atlas.</p></div>${profile?'<button id="newTopic">+ Nuevo tema</button>':''}</div><div class="topicList">${(d.topics||[]).length?(d.topics||[]).map(x=>`<button class="topicCard" data-topic="${x.id}"><span class="genderAvatar ${esc(x.gender)}">${avatar(x.gender)}</span><div><small>${esc(x.alias)} · ${who(x.gender)}</small><strong>${esc(x.title)}</strong><p>${esc(x.body)}</p><em>💬 ${x.reply_count||0} respuestas · ${esc(when(x.created_at))}</em></div></button>`).join(''):'<div class="emptySocial">🧠 No hay debates todavía. Crea el primero.</div>'}</div>${!profile?'<button class="lockedSocial" id="lockedSocial">🔒 Elige tu identidad arriba para abrir un debate</button>':''}`;q('#newTopic')?.addEventListener('click',newTopic);q('#lockedSocial')?.addEventListener('click',()=>q('#profileBox').scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>openTopic(Number(b.dataset.topic)))}catch{body.innerHTML='<div class="emptySocial">No fue posible cargar los debates.</div>'}}
function newTopic(){q('#communityBody').innerHTML=`<button class="backTopics" id="backTopics">← Volver</button><form class="topicForm" id="topicForm"><h3>Nuevo debate</h3><label>Título <span id="titleCount">0 / 100</span></label><input id="topicTitle" minlength="4" maxlength="100" required placeholder="Ej: ¿Qué IA te sorprendió este año?"><label>Tu idea <span id="bodyCount">0 / 600</span></label><textarea id="topicBody" minlength="8" maxlength="600" rows="6" required placeholder="Explica tu punto de vista o propuesta…"></textarea><button>Publicar debate →</button></form>`;q('#backTopics').onclick=()=>loadTopics();['topicTitle','topicBody'].forEach(id=>q('#'+id).oninput=()=>q(id==='topicTitle'?'#titleCount':'#bodyCount').textContent=`${q('#'+id).value.length} / ${id==='topicTitle'?100:600}`);q('#topicForm').onsubmit=async e=>{e.preventDefault();try{await call('create_topic',{visitor_id:visitor,alias:profile.alias,gender:profile.gender,title:q('#topicTitle').value,body:q('#topicBody').value});loadTopics()}catch(err){alert(err.code==='unsafe_content'?'El contenido fue bloqueado por seguridad.':'No se pudo publicar. Revisa el texto o intenta en unos segundos.')}}}
async function openTopic(id){topicId=id;q('#communityBody').innerHTML='<div class="communityLoading">Abriendo debate…</div>';try{const d=await call('topic_replies',{topic_id:id});q('#communityBody').innerHTML=`<button class="backTopics" id="backTopics">← Debates</button><article class="topicOpen"><header><span class="genderAvatar ${esc(d.topic.gender)}">${avatar(d.topic.gender)}</span><div><small>${esc(d.topic.alias)} · ${who(d.topic.gender)}</small><h3>${esc(d.topic.title)}</h3><time>${esc(when(d.topic.created_at))}</time></div></header><p>${esc(d.topic.body)}</p><button class="reportText" data-report="topic" data-id="${d.topic.id}">⚑ Reportar</button></article><div class="replyList">${(d.replies||[]).map(r=>`<article class="reply"><span class="genderAvatar ${esc(r.gender)}">${avatar(r.gender)}</span><div><b>${esc(r.alias)}</b><small>${who(r.gender)} · ${esc(when(r.created_at))}</small><p>${esc(r.message)}</p><button class="reportBtn" data-report="reply" data-id="${r.id}">⚑</button></div></article>`).join('')}</div>${profile?`<form class="replyForm" id="replyForm"><textarea id="replyInput" maxlength="400" rows="3" placeholder="Responde al debate…"></textarea><div><span id="replyCount">0 / 400</span><button>Responder</button></div></form>`:'<button class="lockedSocial" id="lockedSocial">🔒 Elige tu identidad para responder</button>'}`;q('#backTopics').onclick=()=>loadTopics();wireReports();const inp=q('#replyInput');if(inp){inp.oninput=()=>q('#replyCount').textContent=`${inp.value.length} / 400`;q('#replyForm').onsubmit=async e=>{e.preventDefault();if(!inp.value.trim())return;try{await call('reply',{visitor_id:visitor,topic_id:id,alias:profile.alias,gender:profile.gender,message:inp.value});openTopic(id)}catch(err){alert(err.code==='unsafe_content'?'Ese contenido fue bloqueado por seguridad.':'No se pudo responder todavía.')}}}}catch{loadTopics()}}
function wireReports(){document.querySelectorAll('[data-report]').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(!confirm('¿Reportar este contenido para revisión?'))return;try{await call('report',{visitor_id:visitor,content_type:b.dataset.report,content_id:Number(b.dataset.id),reason:'Reporte comunitario'});b.textContent='✓ Reportado';b.disabled=true}catch{}})}
function maybeNudge(){const last=Number(localStorage.getItem(K.reminder)||0),day=86400000;if(Date.now()-last<day)return;setTimeout(()=>{const n=q('#atlasNudge');if(!n)return;n.classList.add('show');localStorage.setItem(K.reminder,String(Date.now()));q('#nudgeClose').onclick=()=>n.classList.remove('show');q('#nudgeLike').onclick=()=>{like();n.classList.remove('show')};q('#nudgeDebate').onclick=()=>{n.classList.remove('show');open();switchTab('forum')}},12000)}
try{navigator.serviceWorker?.register('./sw.js')}catch{}
shell();
})();