/* AI World Atlas — comunidad anónima: chat, debates, likes y recordatorio 24 h. */
(function(){
const mount=document.getElementById('communityMount');
const cfg=window.ATLAS_BACKEND;
if(!mount||!cfg||!cfg.url||!cfg.key||!window.supabase)return;

const client=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const VISITOR_KEY='aiWorldAtlasVisitorIdV1';
const LIKED_KEY='aiWorldAtlasLikedV1';
const PROFILE_KEY='aiWorldAtlasChatProfileV1';
const REMINDER_KEY='aiWorldAtlasCommunityReminderV2';
const DAY=24*60*60*1000;
const EMOJIS=['😀','😂','😍','🤩','😎','🤖','👋','🔥','✨','💙','❤️','👍','👏','🚀','🌎','💡','🧠','🎉','😅','🤔','👀','🙌','💻','🎨'];
const NAMES={
 boy:['CapitánPrompt','ByteBandido','DonDato','Señor404','AstroCoder','PixelPirata','NinjaNeuronal','RobotConCafé','CazadorDeBugs','MagoDelToken','LordLatencia','ProfePrompt','ComandanteByte','AgenteVector','CerebroTurbo','PandaProgramador'],
 girl:['ReinaPrompt','DamaDeDatos','LunaByte','PixelNinja','AdaTurbo','CiberLuna','MagaDelToken','NovaCoder','GataCuántica','CapitanaContexto','Señora404','NubeTraviesa','DoctoraPrompt','EstrellaVector','RobotConTacones','SirenaDigital']
};
const COPY={
 es:{community:'Comunidad AI World Atlas',lead:'Un espacio anónimo para conversar sobre inteligencia artificial, compartir ideas y debatir con otras personas sin crear una cuenta.',chat:'Chat en vivo',debates:'Debates IA',visitors:'Visitantes',online:'En vivo',likes:'Me gusta',topics:'Debates',like:'♥ Me gusta',liked:'♥ Te gusta',joinTitle:'Elige tu identidad divertida',joinText:'Solo necesitamos saber si eres chico o chica. Puedes escribir un apodo o dejar que el Atlas invente uno.',boy:'Chico',girl:'Chica',nickname:'Tu apodo (opcional)',random:'🎲 Sorpréndeme',enter:'Entrar anónimo',change:'Cambiar',room:'Sala general',history:'El historial se conserva',emptyChat:'Todavía no hay mensajes. Rompe el hielo.',message:'Escribe un mensaje…',send:'Enviar',older:'Mensajes anteriores',newTopic:'Nuevo debate',emptyForum:'Todavía no hay debates. Puedes abrir el primero.',topicTitle:'Título del debate',topicBody:'¿Qué quieres plantear a la comunidad?',publish:'Publicar debate',cancel:'Cancelar',reply:'Responder',replyHint:'Escribe tu respuesta…',back:'← Volver a debates',report:'Reportar',reported:'Reporte recibido. Gracias.',safe:'Protección comunitaria',safeText:'El contenido se trata como texto, se limita por longitud y pasa por validación del servidor. Scripts, HTML ejecutable y patrones de inyección se rechazan.',remTitle:'¿Te está sirviendo el Atlas?',remText:'Si te gusta la página, deja un ♥ y comparte tu opinión en los debates. Este recordatorio aparece como máximo una vez cada 24 horas en este navegador.',remLike:'♥ Dar me gusta',remDiscuss:'💬 Dejar mi opinión',later:'Ahora no',unsafe:'Por seguridad no se permiten scripts, HTML ejecutable ni patrones de inyección.',rate:'Vas muy rápido. Espera un momento antes de volver a publicar.',error:'No fue posible completar la acción. Inténtalo nuevamente.',needIdentity:'Elige Chico o Chica y un apodo antes de publicar.'},
 en:{community:'AI World Atlas Community',lead:'An anonymous space to talk about artificial intelligence, share ideas and debate with other people without creating an account.',chat:'Live chat',debates:'AI debates',visitors:'Visitors',online:'Live',likes:'Likes',topics:'Debates',like:'♥ Like',liked:'♥ Liked',joinTitle:'Choose your fun identity',joinText:'Just tell us whether you are a boy or girl. Write a nickname or let the Atlas invent one.',boy:'Boy',girl:'Girl',nickname:'Nickname (optional)',random:'🎲 Surprise me',enter:'Enter anonymously',change:'Change',room:'General room',history:'History is kept',emptyChat:'No messages yet. Break the ice.',message:'Write a message…',send:'Send',older:'Earlier messages',newTopic:'New debate',emptyForum:'No debates yet. You can start the first one.',topicTitle:'Debate title',topicBody:'What would you like to discuss?',publish:'Publish debate',cancel:'Cancel',reply:'Reply',replyHint:'Write your reply…',back:'← Back to debates',report:'Report',reported:'Report received. Thank you.',safe:'Community protection',safeText:'Content is treated as text, length-limited and validated by the server. Executable HTML, scripts and injection patterns are rejected.',remTitle:'Is the Atlas useful to you?',remText:'If you like the page, leave a ♥ and share your opinion in the debates. This reminder appears at most once every 24 hours in this browser.',remLike:'♥ Like this page',remDiscuss:'💬 Share my opinion',later:'Not now',unsafe:'For security, scripts, executable HTML and injection patterns are not allowed.',rate:'You are posting too quickly. Wait a moment and try again.',error:'The action could not be completed. Try again.',needIdentity:'Choose Boy or Girl and a nickname before posting.'},
 fil:{community:'Komunidad ng AI World Atlas',lead:'Anonymous na espasyo para pag-usapan ang artificial intelligence, magbahagi ng ideya at makipagdebate nang walang account.',chat:'Live chat',debates:'AI debates',visitors:'Mga bisita',online:'Live',likes:'Mga like',topics:'Debates',like:'♥ Like',liked:'♥ Nag-like ka',joinTitle:'Pumili ng masayang identity',joinText:'Piliin kung lalaki o babae. Maaari kang gumawa ng palayaw o hayaan ang Atlas na pumili.',boy:'Lalaki',girl:'Babae',nickname:'Palayaw (opsyonal)',random:'🎲 Sorpresahin ako',enter:'Pumasok nang anonymous',change:'Palitan',room:'General room',history:'Nananatili ang history',emptyChat:'Wala pang mensahe. Mauna ka.',message:'Sumulat ng mensahe…',send:'Ipadala',older:'Mas lumang mensahe',newTopic:'Bagong debate',emptyForum:'Wala pang debate. Maaari kang mauna.',topicTitle:'Pamagat ng debate',topicBody:'Ano ang gusto mong pag-usapan?',publish:'I-publish',cancel:'Kanselahin',reply:'Sumagot',replyHint:'Isulat ang sagot…',back:'← Bumalik sa debates',report:'I-report',reported:'Natanggap ang report. Salamat.',safe:'Proteksyon ng komunidad',safeText:'Text lamang ang nilalaman, may limitasyon sa haba at server validation. Hindi pinapayagan ang executable HTML, scripts at injection patterns.',remTitle:'Nakatutulong ba ang Atlas?',remText:'Kung gusto mo ang page, mag-iwan ng ♥ at ibahagi ang opinyon mo sa debates. Isang beses lang ito lalabas bawat 24 oras sa browser na ito.',remLike:'♥ Mag-like',remDiscuss:'💬 Magbigay ng opinyon',later:'Hindi muna',unsafe:'Para sa seguridad, hindi pinapayagan ang scripts, executable HTML at injection patterns.',rate:'Masyado kang mabilis. Maghintay sandali bago muling mag-post.',error:'Hindi nakumpleto ang aksyon. Subukan muli.',needIdentity:'Piliin ang Lalaki o Babae at palayaw bago mag-post.'}
};

let visitorId=localStorage.getItem(VISITOR_KEY);
if(!visitorId){visitorId=crypto.randomUUID();localStorage.setItem(VISITOR_KEY,visitorId)}
let profile=readProfile();
let pendingGender=profile?.gender||'';
let activeTab='chat';
let activeTopicId=null;
let messages=[];
let topics=[];
let hasMore=false;
let oldestCursor=null;
let panelOpen=false;
let chatTimer=null;

function lang(){return localStorage.getItem('aiWorldAtlasLanguageV1')||'es'}
function t(k){return (COPY[lang()]||COPY.es)[k]||k}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function readProfile(){try{const p=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');return p&&['boy','girl'].includes(p.gender)&&p.alias?{gender:p.gender,alias:String(p.alias).slice(0,24)}:null}catch(_e){return null}}
function saveProfile(p){profile=p;pendingGender=p.gender;localStorage.setItem(PROFILE_KEY,JSON.stringify(p))}
function randomName(){const g=pendingGender||(['boy','girl'][Math.floor(Math.random()*2)]);const pool=NAMES[g];return pool[Math.floor(Math.random()*pool.length)]}
function avatar(g){return g==='girl'?'👩':g==='boy'?'👨':'🙂'}
function genderLabel(g){return g==='girl'?`👩 ${t('girl')}`:g==='boy'?`👨 ${t('boy')}`:'🙂'}
function formatTime(value){try{const d=new Date(value);const same=d.toDateString()===new Date().toDateString();return new Intl.DateTimeFormat(lang()==='en'?'en-US':lang()==='fil'?'fil-PH':'es-CO',same?{hour:'2-digit',minute:'2-digit'}:{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)}catch(_e){return ''}}
function num(v){return Number(v||0).toLocaleString(lang()==='en'?'en-US':lang()==='fil'?'fil-PH':'es-CO')}
async function invoke(action,extra={}){
  const {data,error}=await client.functions.invoke('atlas-community',{body:{action,...extra}});
  if(error){let code='';try{if(error.context&&typeof error.context.json==='function'){const body=await error.context.json();code=String(body?.error||'')}}catch(_e){}throw new Error(code||error.message||'request_failed')}
  if(data?.error)throw new Error(String(data.error));
  return data||{};
}
async function ping(){try{await client.functions.invoke('atlas-visit',{body:{visitor_id:visitorId}})}catch(_e){}}
function friendlyError(err){const m=String(err?.message||err||'');if(m.includes('unsafe_content'))return t('unsafe');if(m.includes('rate_limited'))return t('rate');return t('error')}
function showToast(text){let el=document.getElementById('communityToast');if(!el){el=document.createElement('div');el.id='communityToast';el.className='communityToast';document.body.appendChild(el)}el.textContent=text;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),2600)}

function createUI(){
  mount.innerHTML=`<section class="communityHub" id="comunidad"><div class="communityHero"><div><div class="communityKicker"><i></i> COMUNIDAD ABIERTA</div><h2>${esc(t('community'))}</h2><p class="communityHubLead">${esc(t('lead'))}</p><div class="communityHubActions"><button class="communityPrimary" id="communityOpenChat">💬 ${esc(t('chat'))}</button><button class="communitySecondary" id="communityOpenForum">🧠 ${esc(t('debates'))}</button><button class="communityLike" id="communityHubLike">${localStorage.getItem(LIKED_KEY)==='1'?esc(t('liked')):esc(t('like'))}</button></div></div><div class="communityMetrics"><div class="communityMetric2"><b id="hubVisitors">—</b><span>👁 ${esc(t('visitors'))}</span></div><div class="communityMetric2"><b id="hubOnline">—</b><span>🟢 ${esc(t('online'))}</span></div><div class="communityMetric2"><b id="hubLikes">—</b><span>♥ ${esc(t('likes'))}</span></div><div class="communityMetric2"><b id="hubTopics">—</b><span>🧠 ${esc(t('topics'))}</span></div></div></div><div class="communitySafety"><span class="communitySafetyIcon">🔒</span><div><strong>${esc(t('safe'))}</strong><br>${esc(t('safeText'))}</div></div></section>`;
  document.body.insertAdjacentHTML('beforeend',`<button class="communityFloat" id="communityFloat" aria-label="${esc(t('community'))}"><span class="communityFloatDot"></span><b>💬 ${esc(t('chat'))}</b><em id="communityFloatOnline">…</em></button><div class="communityBackdrop2" id="communityBackdrop2"></div><aside class="communityPanel2" id="communityPanel2" aria-hidden="true"><div class="communityPanelHead"><div class="communityPanelLogo">🌐</div><div><small>AI WORLD ATLAS</small><h2>${esc(t('community'))}</h2><p>${esc(t('lead'))}</p></div><button class="communityClose" id="communityClose" aria-label="Cerrar">×</button></div><div class="communityTabs"><button class="communityTab active" data-tab="chat">💬 ${esc(t('chat'))}</button><button class="communityTab" data-tab="forum">🧠 ${esc(t('debates'))}</button></div><div class="communityPanelStats"><div class="communityMiniStat"><b id="panelVisitors">—</b><span>${esc(t('visitors'))}</span></div><div class="communityMiniStat"><b id="panelOnline">—</b><span>${esc(t('online'))}</span></div><div class="communityMiniStat"><b id="panelLikes">—</b><span>${esc(t('likes'))}</span></div><div class="communityMiniStat"><b id="panelTopics">—</b><span>${esc(t('topics'))}</span></div></div><div class="communityIdentityArea" id="communityIdentityArea"></div><div class="communityView" id="communityView"></div></aside>`);
  document.getElementById('communityOpenChat').onclick=()=>openPanel('chat');
  document.getElementById('communityOpenForum').onclick=()=>openPanel('forum');
  document.getElementById('communityHubLike').onclick=likeSite;
  document.getElementById('communityFloat').onclick=()=>openPanel('chat');
  document.getElementById('communityClose').onclick=closePanel;
  document.getElementById('communityBackdrop2').onclick=closePanel;
  document.querySelectorAll('.communityTab').forEach(btn=>btn.onclick=()=>switchTab(btn.dataset.tab));
  renderIdentity();
  renderChat();
  installDelegation();
}
function installDelegation(){
  const panel=document.getElementById('communityPanel2');
  panel.addEventListener('click',e=>{
    const topic=e.target.closest('[data-topic-id]');if(topic&&!e.target.closest('[data-report-type]')){openTopic(Number(topic.dataset.topicId));return}
    const report=e.target.closest('[data-report-type]');if(report){e.stopPropagation();reportContent(report.dataset.reportType,Number(report.dataset.reportId));return}
  });
}
function openPanel(tab='chat'){panelOpen=true;document.getElementById('communityPanel2').classList.add('show');document.getElementById('communityPanel2').setAttribute('aria-hidden','false');document.getElementById('communityBackdrop2').classList.add('show');switchTab(tab);loadStats();startPolling()}
function closePanel(){panelOpen=false;document.getElementById('communityPanel2')?.classList.remove('show');document.getElementById('communityPanel2')?.setAttribute('aria-hidden','true');document.getElementById('communityBackdrop2')?.classList.remove('show');stopPolling()}
function switchTab(tab){activeTab=tab==='forum'?'forum':'chat';activeTopicId=null;document.querySelectorAll('.communityTab').forEach(b=>b.classList.toggle('active',b.dataset.tab===activeTab));if(activeTab==='chat'){renderChat();loadMessages(true)}else{renderForum();loadTopics()};startPolling()}
function startPolling(){stopPolling();if(!panelOpen)return;chatTimer=setInterval(()=>{if(activeTab==='chat')loadMessages(true,true);else if(!activeTopicId)loadTopics(true);loadStats()},6000)}
function stopPolling(){if(chatTimer){clearInterval(chatTimer);chatTimer=null}}

function renderIdentity(){
  const box=document.getElementById('communityIdentityArea');if(!box)return;
  if(profile){box.innerHTML=`<div class="communityIdentity"><div class="communityAvatar ${esc(profile.gender)}">${avatar(profile.gender)}</div><div><span>${esc(genderLabel(profile.gender))}</span><strong>${esc(profile.alias)}</strong></div><button id="communityChangeProfile">${esc(t('change'))}</button></div>`;document.getElementById('communityChangeProfile').onclick=()=>{profile=null;pendingGender='';localStorage.removeItem(PROFILE_KEY);renderIdentity();renderActiveView()};return}
  box.innerHTML=`<div class="communityJoin"><div class="communityJoinTop"><span>✨</span><div><strong>${esc(t('joinTitle'))}</strong><p>${esc(t('joinText'))}</p></div></div><div class="communityGenderChoices"><button class="communityGenderBtn boy ${pendingGender==='boy'?'active':''}" data-gender="boy">👨 ${esc(t('boy'))}</button><button class="communityGenderBtn girl ${pendingGender==='girl'?'active':''}" data-gender="girl">👩 ${esc(t('girl'))}</button></div><div class="communityAliasRow"><input id="communityAlias" maxlength="24" autocomplete="off" placeholder="${esc(t('nickname'))}"><button id="communityRandom">${esc(t('random'))}</button></div><button class="communityEnter" id="communityEnter">${esc(t('enter'))} →</button></div>`;
  box.querySelectorAll('[data-gender]').forEach(btn=>btn.onclick=()=>{pendingGender=btn.dataset.gender;renderIdentity()});
  document.getElementById('communityRandom').onclick=()=>{const input=document.getElementById('communityAlias');input.value=randomName()};
  document.getElementById('communityEnter').onclick=()=>{if(!pendingGender){showToast(t('needIdentity'));return}const input=document.getElementById('communityAlias');const alias=(input?.value||'').trim().slice(0,24)||randomName();saveProfile({gender:pendingGender,alias});renderIdentity();renderActiveView()};
}
function ensureProfile(){if(profile)return true;showToast(t('needIdentity'));document.getElementById('communityIdentityArea')?.scrollIntoView({behavior:'smooth',block:'nearest'});return false}
function renderActiveView(){activeTab==='chat'?renderChat():renderForum()}

async function loadStats(){try{const data=await invoke('stats');setStat('Visitors',data.visitors_total);setStat('Online',data.visitors_online);setStat('Likes',data.likes_total);setStat('Topics',data.topics_total);const f=document.getElementById('communityFloatOnline');if(f)f.textContent=`${num(data.visitors_online)} ${t('online').toLowerCase()}`;const like=document.getElementById('communityHubLike');if(like)like.textContent=localStorage.getItem(LIKED_KEY)==='1'?t('liked'):t('like')}catch(_e){const f=document.getElementById('communityFloatOnline');if(f)f.textContent=t('online')}}
function setStat(name,value){const v=num(value);const a=document.getElementById('hub'+name),b=document.getElementById('panel'+name);if(a)a.textContent=v;if(b)b.textContent=v}
async function likeSite(){if(localStorage.getItem(LIKED_KEY)==='1'){showToast(t('liked'));return}try{await invoke('like',{visitor_id:visitorId});localStorage.setItem(LIKED_KEY,'1');showToast('♥ '+t('liked').replace(/^♥\s*/,''));await loadStats()}catch(err){showToast(friendlyError(err))}}

function renderChat(){
  const view=document.getElementById('communityView');if(!view)return;
  view.innerHTML=`<div class="communityRoomBar"><span>💬 <strong>${esc(t('room'))}</strong></span><span><i></i><b id="roomOnline">—</b></span></div><div class="communityMessages" id="communityMessages"><div class="communityEmpty">${esc(t('emptyChat'))}</div></div><div class="communityComposerWrap"><div class="emojiTray2" id="emojiTray2">${EMOJIS.map(e=>`<button type="button" data-emoji="${e}">${e}</button>`).join('')}</div><form class="communityComposer" id="communityChatForm"><button type="button" class="emojiButton" id="communityEmoji">😊</button><input id="communityChatText" maxlength="500" autocomplete="off" placeholder="${esc(t('message'))}" ${profile?'':'disabled'}><button class="communitySend" id="communityChatSend" ${profile?'':'disabled'}>${esc(t('send'))}</button></form><div class="charLine"><span class="sendState" id="chatState">${profile?'':esc(t('needIdentity'))}</span><span id="chatCount">0/500</span></div></div>`;
  document.getElementById('communityChatForm').onsubmit=sendMessage;
  const input=document.getElementById('communityChatText');input?.addEventListener('input',()=>document.getElementById('chatCount').textContent=`${input.value.length}/500`);
  document.getElementById('communityEmoji').onclick=()=>document.getElementById('emojiTray2').classList.toggle('show');
  document.querySelectorAll('#emojiTray2 [data-emoji]').forEach(btn=>btn.onclick=()=>insertEmoji(input,btn.dataset.emoji));
  if(messages.length)renderMessages(false);else loadMessages(true);
}
function insertEmoji(input,emoji){if(!input||input.disabled)return;const start=input.selectionStart??input.value.length,end=input.selectionEnd??start;if(input.value.length+emoji.length>Number(input.maxLength))return;input.value=input.value.slice(0,start)+emoji+input.value.slice(end);input.focus();input.selectionStart=input.selectionEnd=start+emoji.length;input.dispatchEvent(new Event('input'))}
async function loadMessages(reset=true,silent=false){
  if(activeTab!=='chat')return;const box=document.getElementById('communityMessages');if(!box)return;
  try{if(reset){const data=await invoke('messages');messages=(data.messages||[]).slice().reverse();hasMore=Boolean(data.has_more);oldestCursor=messages[0]?.created_at||null;renderMessages(!silent)}else if(oldestCursor){const before=box.scrollHeight;const data=await invoke('messages',{before:oldestCursor});const older=(data.messages||[]).slice().reverse();messages=[...older,...messages];hasMore=Boolean(data.has_more);oldestCursor=messages[0]?.created_at||oldestCursor;renderMessages(false);box.scrollTop=box.scrollHeight-before}}catch(err){if(!silent&&messages.length===0)box.innerHTML=`<div class="communityEmpty">⚠️ ${esc(friendlyError(err))}</div>`}}
function renderMessages(scroll=true){const box=document.getElementById('communityMessages');if(!box)return;let html=hasMore?`<button class="communityLoadMore" id="communityLoadOlder">↑ ${esc(t('older'))}</button>`:'';if(!messages.length)html+=`<div class="communityEmpty">💬 ${esc(t('emptyChat'))}</div>`;else html+=messages.map(m=>`<div class="communityMessage"><div class="communityAvatar ${esc(m.gender)}">${avatar(m.gender)}</div><div class="communityBubble"><div class="communityMeta"><strong>${esc(m.alias)}</strong><span class="genderTag ${esc(m.gender)}">${esc(genderLabel(m.gender))}</span><button class="reportBtn" data-report-type="chat" data-report-id="${Number(m.id)}" title="${esc(t('report'))}">⚑</button><time>${esc(formatTime(m.created_at))}</time></div><p>${esc(m.message)}</p></div></div>`).join('');box.innerHTML=html;document.getElementById('communityLoadOlder')?.addEventListener('click',()=>loadMessages(false));if(scroll)box.scrollTop=box.scrollHeight}
async function sendMessage(e){e.preventDefault();if(!ensureProfile())return;const input=document.getElementById('communityChatText'),button=document.getElementById('communityChatSend'),state=document.getElementById('chatState');const message=(input?.value||'').trim();if(!message)return;button.disabled=true;state.textContent='…';state.className='sendState';try{await invoke('send',{visitor_id:visitorId,alias:profile.alias,gender:profile.gender,message});input.value='';input.dispatchEvent(new Event('input'));state.textContent='✓';state.className='sendState ok';await loadMessages(true)}catch(err){state.textContent=friendlyError(err);state.className='sendState error'}finally{button.disabled=false;input?.focus()}}

function renderForum(){
  const view=document.getElementById('communityView');if(!view)return;
  view.innerHTML=`<div class="forumToolbar"><div><strong>🧠 ${esc(t('debates'))}</strong><span>Ideas, preguntas y opiniones sobre inteligencia artificial.</span></div><button class="forumNewBtn" id="forumNewBtn">＋ ${esc(t('newTopic'))}</button></div><div id="forumFormMount"></div><div class="forumList" id="forumList"><div class="communityEmpty">Cargando…</div></div>`;
  document.getElementById('forumNewBtn').onclick=showNewTopicForm;
  if(topics.length)renderTopics();else loadTopics();
}
async function loadTopics(silent=false){if(activeTab!=='forum'||activeTopicId)return;const list=document.getElementById('forumList');if(!list)return;try{const data=await invoke('topics');topics=data.topics||[];renderTopics()}catch(err){if(!silent)list.innerHTML=`<div class="communityEmpty">⚠️ ${esc(friendlyError(err))}</div>`}}
function renderTopics(){const list=document.getElementById('forumList');if(!list)return;if(!topics.length){list.innerHTML=`<div class="communityEmpty">🧠 ${esc(t('emptyForum'))}</div>`;return}list.innerHTML=topics.map(x=>`<article class="forumCard" data-topic-id="${Number(x.id)}"><div class="forumCardHead"><strong>${esc(x.alias)}</strong><span class="genderTag ${esc(x.gender)}">${esc(genderLabel(x.gender))}</span><button class="reportBtn" data-report-type="topic" data-report-id="${Number(x.id)}" title="${esc(t('report'))}">⚑</button><time>${esc(formatTime(x.created_at))}</time></div><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><div class="forumCardFoot"><span>💬 ${num(x.reply_count)} ${esc(t('reply').toLowerCase())}</span><span>Entrar →</span></div></article>`).join('')}
function showNewTopicForm(){if(!ensureProfile())return;const m=document.getElementById('forumFormMount');if(!m)return;m.innerHTML=`<form class="forumForm" id="newTopicForm"><h3>✨ ${esc(t('newTopic'))}</h3><input id="topicTitle" maxlength="100" placeholder="${esc(t('topicTitle'))}" autocomplete="off"><div class="charLine"><span></span><span id="topicTitleCount">0/100</span></div><textarea id="topicBody" maxlength="600" placeholder="${esc(t('topicBody'))}"></textarea><div class="charLine"><span class="sendState" id="topicState"></span><span id="topicBodyCount">0/600</span></div><div class="forumFormActions"><button type="button" class="forumCancel" id="forumCancel">${esc(t('cancel'))}</button><button class="forumPublish" id="forumPublish">${esc(t('publish'))}</button></div></form>`;const title=document.getElementById('topicTitle'),body=document.getElementById('topicBody');title.oninput=()=>document.getElementById('topicTitleCount').textContent=`${title.value.length}/100`;body.oninput=()=>document.getElementById('topicBodyCount').textContent=`${body.value.length}/600`;document.getElementById('forumCancel').onclick=()=>m.innerHTML='';document.getElementById('newTopicForm').onsubmit=createTopic;title.focus()}
async function createTopic(e){e.preventDefault();if(!ensureProfile())return;const title=document.getElementById('topicTitle'),body=document.getElementById('topicBody'),state=document.getElementById('topicState'),btn=document.getElementById('forumPublish');const titleText=(title?.value||'').trim(),bodyText=(body?.value||'').trim();if(titleText.length<4||bodyText.length<8){state.textContent='Completa el título y la idea antes de publicar.';state.className='sendState error';return}btn.disabled=true;try{const data=await invoke('create_topic',{visitor_id:visitorId,alias:profile.alias,gender:profile.gender,title:titleText,body:bodyText});document.getElementById('forumFormMount').innerHTML='';showToast('✓ '+t('publish'));await loadStats();await loadTopics();if(data.topic?.id)openTopic(Number(data.topic.id))}catch(err){state.textContent=friendlyError(err);state.className='sendState error'}finally{btn.disabled=false}}
async function openTopic(id){activeTopicId=id;const view=document.getElementById('communityView');if(!view)return;view.innerHTML=`<div class="communityEmpty">Cargando debate…</div>`;try{const data=await invoke('topic_replies',{topic_id:id});renderTopicView(data.topic,data.replies||[])}catch(err){view.innerHTML=`<button class="topicBack" id="topicBack">${esc(t('back'))}</button><div class="communityEmpty">⚠️ ${esc(friendlyError(err))}</div>`;document.getElementById('topicBack').onclick=()=>{activeTopicId=null;renderForum();loadTopics()}}}
function renderTopicView(topic,replies){const view=document.getElementById('communityView');if(!view)return;view.innerHTML=`<div class="topicView"><button class="topicBack" id="topicBack">${esc(t('back'))}</button><article class="topicCardMain"><div class="communityMeta"><strong>${esc(topic.alias)}</strong><span class="genderTag ${esc(topic.gender)}">${esc(genderLabel(topic.gender))}</span><button class="reportBtn" data-report-type="topic" data-report-id="${Number(topic.id)}" title="${esc(t('report'))}">⚑</button><time>${esc(formatTime(topic.created_at))}</time></div><h3>${esc(topic.title)}</h3><p>${esc(topic.body)}</p></article><div class="topicReplies" id="topicReplies">${replies.length?replies.map(r=>`<article class="topicReply"><div class="communityMeta"><strong>${esc(r.alias)}</strong><span class="genderTag ${esc(r.gender)}">${esc(genderLabel(r.gender))}</span><button class="reportBtn" data-report-type="reply" data-report-id="${Number(r.id)}" title="${esc(t('report'))}">⚑</button><time>${esc(formatTime(r.created_at))}</time></div><p>${esc(r.message)}</p></article>`).join(''):`<div class="communityEmpty">Sé la primera persona en responder.</div>`}</div><form class="topicReplyForm" id="topicReplyForm"><textarea id="topicReplyText" maxlength="400" placeholder="${esc(t('replyHint'))}" ${profile?'':'disabled'}></textarea><div class="topicReplyActions"><span class="sendState" id="replyState">${profile?'':esc(t('needIdentity'))}</span><span><small id="replyCount">0/400</small> <button ${profile?'':'disabled'}>${esc(t('reply'))}</button></span></div></form></div>`;document.getElementById('topicBack').onclick=()=>{activeTopicId=null;renderForum();loadTopics()};const input=document.getElementById('topicReplyText');input?.addEventListener('input',()=>document.getElementById('replyCount').textContent=`${input.value.length}/400`);document.getElementById('topicReplyForm').onsubmit=e=>sendReply(e,topic.id)}
async function sendReply(e,topicId){e.preventDefault();if(!ensureProfile())return;const input=document.getElementById('topicReplyText'),state=document.getElementById('replyState'),button=e.currentTarget.querySelector('button');const message=(input?.value||'').trim();if(message.length<2)return;button.disabled=true;try{await invoke('reply',{visitor_id:visitorId,topic_id:topicId,alias:profile.alias,gender:profile.gender,message});await openTopic(topicId);await loadStats()}catch(err){state.textContent=friendlyError(err);state.className='sendState error'}finally{button.disabled=false}}
async function reportContent(type,id){try{await invoke('report',{visitor_id:visitorId,content_type:type,content_id:id,reason:'Reporte desde la comunidad'});showToast(t('reported'))}catch(err){showToast(friendlyError(err))}}

function maybeReminder(){const last=Number(localStorage.getItem(REMINDER_KEY)||0);if(Date.now()-last<DAY)return;setTimeout(()=>{if(document.getElementById('communityReminder'))return;localStorage.setItem(REMINDER_KEY,String(Date.now()));const liked=localStorage.getItem(LIKED_KEY)==='1';document.body.insertAdjacentHTML('beforeend',`<div class="communityReminder" id="communityReminder"><div class="communityReminderTop"><div class="communityReminderIcon">${liked?'💬':'♥'}</div><div><h3>${esc(t('remTitle'))}</h3><p>${esc(t('remText'))}</p></div></div><div class="communityReminderActions">${liked?'':`<button class="remLike" id="remLike">${esc(t('remLike'))}</button>`}<button class="remDiscuss" id="remDiscuss">${esc(t('remDiscuss'))}</button><button class="remClose" id="remClose">${esc(t('later'))}</button></div></div>`);const el=document.getElementById('communityReminder');requestAnimationFrame(()=>el.classList.add('show'));document.getElementById('remLike')?.addEventListener('click',async()=>{await likeSite();hideReminder()});document.getElementById('remDiscuss').onclick=()=>{hideReminder();openPanel('forum')};document.getElementById('remClose').onclick=hideReminder},14000)}
function hideReminder(){const el=document.getElementById('communityReminder');if(!el)return;el.classList.remove('show');setTimeout(()=>el.remove(),220)}

createUI();
ping();loadStats();loadMessages(true);maybeReminder();
setInterval(ping,60000);setInterval(loadStats,30000);
window.addEventListener('storage',e=>{if(e.key===LIKED_KEY)loadStats()});
})();