/* Funciones comunitarias. Solo se activan cuando existe window.ATLAS_BACKEND con Supabase configurado. */
(function(){
const mount=document.getElementById('communityMount');
const cfg=window.ATLAS_BACKEND;
if(!mount||!cfg||!cfg.url||!cfg.key||!window.supabase){return}
const client=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:false}});
const VISITOR_KEY='aiWorldAtlasVisitorIdV1';
let visitorId=localStorage.getItem(VISITOR_KEY);if(!visitorId){visitorId=crypto.randomUUID();localStorage.setItem(VISITOR_KEY,visitorId)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function ping(){try{await client.functions.invoke('atlas-visit',{body:{visitor_id:visitorId}})}catch(e){console.warn('Atlas visit unavailable')}}
async function loadStats(){try{const {data,error}=await client.from('public_stats').select('*').single();if(error)throw error;const total=data?.visitors_total??0,online=data?.visitors_online??0,likes=data?.likes_total??0;mount.innerHTML=`<div class="communityPanel"><h3>Comunidad global</h3><p class="sub">Estadísticas agregadas y respetuosas con la privacidad.</p><div class="communityGrid"><div class="communityMetric"><b>${total}</b><span>Visitantes</span></div><div class="communityMetric"><b>${online}</b><span>Conectados ahora</span></div><div class="communityMetric"><b>${likes}</b><span>♥ Me gusta</span></div></div><div class="cardActionRow"><button class="secondaryBtn" id="atlasLikeBtn">♥ Me gusta el Atlas</button><button class="secondaryBtn" id="atlasChatBtn">Abrir chat global</button></div><div id="atlasGeo"></div><div id="atlasChat" style="display:none"></div></div>`;document.getElementById('atlasLikeBtn')?.addEventListener('click',likeSite);document.getElementById('atlasChatBtn')?.addEventListener('click',openChat);loadGeo()}catch(e){console.warn('Community stats unavailable',e)}}
async function loadGeo(){const {data}=await client.from('continent_stats').select('*');const box=document.getElementById('atlasGeo');if(!box||!data?.length)return;box.innerHTML=`<div class="detailBlock"><h4>Visitantes del mundo</h4>${data.map(x=>`<div class="weight"><div><strong>${esc(x.continent)}</strong><div class="bar"><span style="width:${Math.max(0,Math.min(100,Number(x.percentage)||0))}%"></span></div></div><b>${Number(x.percentage||0).toFixed(0)}%</b></div>`).join('')}</div>`}
async function likeSite(){await client.from('site_likes').upsert({visitor_id:visitorId},{onConflict:'visitor_id',ignoreDuplicates:true});loadStats()}
async function openChat(){const box=document.getElementById('atlasChat');if(!box)return;box.style.display='block';box.innerHTML=`<div class="detailBlock"><h4>Chat global</h4><input id="chatAlias" maxlength="24" placeholder="Alias temporal" class="chatInput"><div id="chatMessages" class="chatMessages"></div><form id="chatForm"><input id="chatText" maxlength="500" placeholder="Escribe un mensaje" class="chatInput"><button class="secondaryBtn">Enviar</button></form></div>`;document.getElementById('chatForm').onsubmit=sendMessage;await loadMessages();client.channel('atlas-chat').on('postgres_changes',{event:'INSERT',schema:'public',table:'chat_messages'},loadMessages).subscribe()}
async function loadMessages(){const {data}=await client.from('chat_messages').select('alias,message,created_at').order('created_at',{ascending:false}).limit(40);const box=document.getElementById('chatMessages');if(box)box.innerHTML=(data||[]).reverse().map(m=>`<p><b>${esc(m.alias)}</b> <span>${esc(m.message)}</span></p>`).join('')}
async function sendMessage(e){e.preventDefault();const alias=(document.getElementById('chatAlias').value||'Visitante').trim().slice(0,24),message=document.getElementById('chatText').value.trim().slice(0,500);if(!message)return;await client.from('chat_messages').insert({visitor_id:visitorId,alias,message});document.getElementById('chatText').value=''}
ping();loadStats();setInterval(ping,60000);
})();
