/* AI World Atlas — UX móvil y avisos de notificaciones. */
(function(){
const cfg=window.ATLAS_BACKEND;if(!cfg?.url||!cfg?.key||!window.supabase)return;
const db=window.supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const K={visitor:'aiWorldAtlasVisitorIdV1',profile:'aiWorldAtlasChatProfileV2',notify:'aiWorldAtlasNotifyV1',lastMsg:'aiWorldAtlasLastMsgV1',lastTopic:'aiWorldAtlasLastTopicV1'};
let visitor=localStorage.getItem(K.visitor)||'',timer=null,baseline=false;
function q(s){return document.querySelector(s)}
function isIOS(){return /iPhone|iPad|iPod/i.test(navigator.userAgent)}
function standalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
function profile(){try{return JSON.parse(localStorage.getItem(K.profile)||'null')}catch{return null}}
async function call(action,extra={}){const {data,error}=await db.functions.invoke('atlas-community',{body:{action,...extra}});if(error)throw error;return data||{}}
function ensureGuide(){if(q('#notifyGuide'))return;document.body.insertAdjacentHTML('beforeend',`<div class="notifyGuide" id="notifyGuide"><div class="notifyGuideCard"><button id="notifyGuideClose">×</button><h3>🔔 Activa las notificaciones</h3><p>En iPhone, las notificaciones web funcionan desde la app web instalada en la pantalla de inicio. Haz esto una vez:</p><div class="notifySteps"><div class="notifyStep"><b>1</b><span>Abre AI World Atlas en Safari.</span></div><div class="notifyStep"><b>2</b><span>Toca <strong>Compartir</strong> y elige <strong>Añadir a pantalla de inicio</strong>.</span></div><div class="notifyStep"><b>3</b><span>Abre el icono del Atlas desde la pantalla de inicio.</span></div><div class="notifyStep"><b>4</b><span>Entra a Comunidad y toca <strong>Activar notificaciones</strong>.</span></div></div></div></div>`);q('#notifyGuideClose').onclick=()=>q('#notifyGuide').classList.remove('show');q('#notifyGuide').onclick=e=>{if(e.target===q('#notifyGuide'))q('#notifyGuide').classList.remove('show')}}
function showGuide(){ensureGuide();q('#notifyGuide').classList.add('show')}
function ensureCard(){const stats=q('.communityStats');if(!stats||q('#communityNotify'))return false;stats.insertAdjacentHTML('afterend','<section class="communityNotify" id="communityNotify"></section>');renderCard();return true}
function renderCard(){const card=q('#communityNotify');if(!card)return;const ios=isIOS(),installed=standalone(),supported='Notification' in window&&'serviceWorker' in navigator;let title='Activa notificaciones',text='Recibe avisos cuando aparezcan mensajes o debates nuevos.',button='Activar';card.className='communityNotify';if(ios&&!installed){title='Notificaciones en iPhone';text='Añade el Atlas a tu pantalla de inicio para habilitarlas.';button='Ver cómo'}else if(!supported){title='Notificaciones no disponibles';text='Este navegador no ofrece notificaciones web aquí.';button='Entendido';card.classList.add('denied')}else if(Notification.permission==='granted'){title='Notificaciones activadas';text='Te avisaremos de actividad nueva mientras el Atlas esté activo.';button='✓ Activas';card.classList.add('granted')}else if(Notification.permission==='denied'){title='Notificaciones bloqueadas';text='Debes habilitarlas desde la configuración del navegador o del sistema.';button='Ayuda';card.classList.add('denied')}card.innerHTML=`<span class="communityNotifyIcon">🔔</span><div><strong>${title}</strong><p>${text}</p></div><button id="notifyAction">${button}</button>`;q('#notifyAction').onclick=activateNotifications}
async function activateNotifications(){if(isIOS()&&!standalone()){showGuide();return}if(!('Notification' in window)){renderCard();return}if(Notification.permission==='denied'){if(isIOS())showGuide();else alert('Las notificaciones están bloqueadas. Habilítalas desde la configuración del navegador para este sitio.');return}if(Notification.permission==='granted'){localStorage.setItem(K.notify,'1');renderCard();await seedBaseline();return}try{const permission=await Notification.requestPermission();if(permission==='granted'){localStorage.setItem(K.notify,'1');await seedBaseline();await showNotification('AI World Atlas','Notificaciones activadas. Te avisaremos cuando haya actividad nueva.','atlas-notify-ready')}renderCard()}catch{renderCard()}}
async function showNotification(title,body,tag){if(!('Notification' in window)||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,tag,renotify:false,icon:'./assets/atlas-hero.png',badge:'./assets/atlas-hero.png',data:{url:location.href.split('#')[0]+'#inicio'}})}catch{try{new Notification(title,{body,tag})}catch{}}}
async function seedBaseline(){try{const [m,t]=await Promise.all([call('messages'),call('topics')]);const lm=m.messages?.[0],lt=t.topics?.[0];if(lm?.id)localStorage.setItem(K.lastMsg,String(lm.id));if(lt?.id)localStorage.setItem(K.lastTopic,String(lt.id));baseline=true}catch{}}
async function checkUpdates(){if(document.visibilityState==='hidden'&&isIOS()&&!standalone())return;if(!('Notification' in window)||Notification.permission!=='granted'||localStorage.getItem(K.notify)!=='1')return;try{const [m,t]=await Promise.all([call('messages'),call('topics')]);const lm=m.messages?.[0],lt=t.topics?.[0];const oldM=Number(localStorage.getItem(K.lastMsg)||0),oldT=Number(localStorage.getItem(K.lastTopic)||0);if(!baseline){if(lm?.id)localStorage.setItem(K.lastMsg,String(lm.id));if(lt?.id)localStorage.setItem(K.lastTopic,String(lt.id));baseline=true;return}const me=profile()?.alias||'';if(lm?.id&&Number(lm.id)>oldM){localStorage.setItem(K.lastMsg,String(lm.id));if(lm.alias!==me)await showNotification(`💬 ${lm.alias||'Nuevo mensaje'}`,String(lm.message||'Hay actividad nueva en el chat').slice(0,110),'atlas-chat-'+lm.id)}if(lt?.id&&Number(lt.id)>oldT){localStorage.setItem(K.lastTopic,String(lt.id));if(lt.alias!==me)await showNotification('🧠 Nuevo debate en AI World Atlas',`${lt.alias||'Alguien'}: ${String(lt.title||'Nuevo tema').slice(0,90)}`,'atlas-topic-'+lt.id)}}catch{}}
function wrapComposer(){const body=q('#communityBody');if(!body)return;const chatForm=q('#chatForm');if(chatForm&&!chatForm.closest('.mobileComposerDock')){const first=q('.emojiLine')||q('.mediaPicker')||chatForm;const wrap=document.createElement('div');wrap.className='mobileComposerDock';first.parentNode.insertBefore(wrap,first);[q('.emojiLine'),q('.mediaPicker'),chatForm].filter(Boolean).forEach(n=>{if(n.parentNode===body)wrap.appendChild(n)})}const reply=q('#replyForm');if(reply&&!reply.closest('.mobileComposerDock')){const picker=[...body.querySelectorAll('.mediaPicker')].find(n=>n.nextElementSibling===reply)||reply.previousElementSibling;const first=picker?.classList?.contains('mediaPicker')?picker:reply;const wrap=document.createElement('div');wrap.className='mobileComposerDock';first.parentNode.insertBefore(wrap,first);if(picker?.classList?.contains('mediaPicker')&&picker.parentNode===body)wrap.appendChild(picker);if(reply.parentNode===body)wrap.appendChild(reply)}}
function focusComposerOnOpen(){const drawer=q('#communityDrawer');if(!drawer)return;drawer.addEventListener('transitionend',()=>{if(window.innerWidth<=600)q('#communityBody')?.scrollTo({top:q('#communityBody').scrollHeight})},{passive:true})}
function observe(){const root=q('#communityDrawer');if(!root)return;const mo=new MutationObserver(()=>{ensureCard();wrapComposer();renderCard()});mo.observe(root,{childList:true,subtree:true});ensureCard();wrapComposer();focusComposerOnOpen()}
function start(){if(!q('#communityDrawer')){requestAnimationFrame(start);return}observe();if(Notification?.permission==='granted'&&localStorage.getItem(K.notify)==='1')seedBaseline();timer=setInterval(checkUpdates,15000)}
start();
})();