const modal=document.querySelector('#modal'), modalContent=document.querySelector('#modalContent');
function openRanking(item){
 modalContent.innerHTML=`<div class="label">Puesto ${item.rank} de la clasificación general</div><h2>${item.name}</h2><div class="company">${item.company} · ${item.country}</div><div class="scoreRow"><div><div class="level">${item.level}</div><div style="margin-top:6px;color:#667085;font-size:12px">Puntuación editorial global</div></div><div class="scoreBig">${item.score}<span style="font-size:13px;color:#98a2b3">/100</span></div></div><div class="detailBlock"><h4>Modelo principal</h4><p>${item.model}</p></div><div class="detailBlock"><h4>Mejor para</h4><p>${item.best}</p></div><div class="detailBlock"><div class="procon"><div><b>Fortalezas</b><p>${item.strengths}</p></div><div><b>Limitaciones</b><p>${item.limits}</p></div></div></div><div class="detailBlock"><h4>Por qué ocupa este puesto</h4><p>${item.why}</p></div><div class="detailBlock"><h4>Referencia independiente</h4><p>${item.aa}</p></div><div class="sourceNote">La puntuación de 0 a 100 es editorial y combina varios criterios. La referencia de Artificial Analysis se muestra por separado para no mezclar una valoración de producto con un benchmark de modelo.</div>`;
 modal.classList.add('show'); document.body.style.overflow='hidden';
}
function openDirectory(item){
 modalContent.innerHTML=`<div class="label">${item.class}</div><h2>${item.name}</h2><div class="company">${item.company} · ${item.country}</div><div class="detailBlock"><h4>Qué es</h4><p>${item.desc}</p></div><div class="detailBlock"><h4>Su mayor fortaleza</h4><p>${item.best}</p></div><div class="detailBlock"><h4>Modelos o tecnología principal</h4><p>${item.model}</p></div><div class="detailBlock"><h4>Apertura</h4><p>${item.open}</p></div><div class="detailBlock"><h4>Capacidades</h4><div class="tags">${item.caps.map(x=>`<span class="tag">${x}</span>`).join('')}</div></div><div class="sourceNote">La clasificación “Modelo propio” significa que la organización desarrolla o entrena modelos principales. No significa necesariamente que fabrique todos los chips o posea toda la infraestructura física utilizada.</div>`;
 modal.classList.add('show'); document.body.style.overflow='hidden';
}
function closeModal(){modal.classList.remove('show');document.body.style.overflow=''}
document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#backdrop').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

function renderRanking(){document.querySelector('#rankingList').innerHTML=ranking.map((x,i)=>`<article class="rankCard"><div class="rankNo ${i<3?'top':''}">#${x.rank}</div><div class="rankName"><h3>${x.name}</h3><p>${x.company} · ${x.model.split(';')[0]}</p><div class="rankMeta"><span class="level">${x.level}</span></div></div><div class="score">${x.score}<small>/100</small></div><div class="rankWhy"><strong style="color:#344054">Su fuerte:</strong> ${x.best}</div><button class="openBtn" onclick="openRanking(ranking[${i}])">Análisis</button></article>`).join('')}

let activeSpecialty=Object.keys(specialties)[0];
function renderSpecialties(){const tabs=document.querySelector('#specialtyTabs');tabs.innerHTML=Object.keys(specialties).map(x=>`<button class="tab ${x===activeSpecialty?'active':''}" onclick="activeSpecialty='${x}';renderSpecialties()">${x}</button>`).join('');document.querySelector('#specialGrid').innerHTML=specialties[activeSpecialty].map(x=>`<article class="specialCard"><div class="pos">Puesto ${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><div class="metric">${x[3]}</div></article>`).join('')}

const search=document.querySelector('#search'),classFilter=document.querySelector('#classFilter'),regionFilter=document.querySelector('#regionFilter'),capFilter=document.querySelector('#capFilter'),sortFilter=document.querySelector('#sortFilter');
[...new Set(directory.map(x=>x.region))].sort().forEach(x=>regionFilter.innerHTML+=`<option>${x}</option>`);
[...new Set(directory.flatMap(x=>x.caps))].sort().forEach(x=>capFilter.innerHTML+=`<option>${x}</option>`);
function renderDirectory(){let s=search.value.trim().toLowerCase(),c=classFilter.value,r=regionFilter.value,k=capFilter.value;let rows=directory.filter(x=>(!s||JSON.stringify(x).toLowerCase().includes(s))&&(!c||x.class===c)&&(!r||x.region===r)&&(!k||x.caps.includes(k)));if(sortFilter.value==='priority'){const p={'Modelo propio':0,'Híbrida':1,'Aplicación sobre terceros':2};rows.sort((a,b)=>p[a.class]-p[b.class]||a.name.localeCompare(b.name))}else if(sortFilter.value==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));else rows.sort((a,b)=>a.country.localeCompare(b.country)||a.name.localeCompare(b.name));document.querySelector('#resultCount').textContent=`${rows.length} resultados`;document.querySelector('#directoryGrid').innerHTML=rows.length?rows.map(x=>{const idx=directory.indexOf(x);return `<article class="card"><div class="cardTop"><div class="avatar">${x.name.replace(/[^A-Za-zÁÉÍÓÚÑ]/g,'').slice(0,2).toUpperCase()}</div><span class="type">${x.class}</span></div><h3>${x.name}</h3><div class="sub">${x.company}</div><p class="desc">${x.desc}</p><p class="best"><strong>Mejor para:</strong> ${x.best}</p><div class="tags">${x.caps.slice(0,5).map(y=>`<span class="tag">${y}</span>`).join('')}</div><div class="cardFooter"><span class="country">${x.country}</span><button class="details" onclick="openDirectory(directory[${idx}])">Ver análisis →</button></div></article>`}).join(''):`<div class="empty">No hay resultados con estos filtros.</div>`}
[search,classFilter,regionFilter,capFilter,sortFilter].forEach(el=>el.addEventListener(el===search?'input':'change',renderDirectory));
document.querySelector('#clearFilters').onclick=()=>{search.value='';classFilter.value='';regionFilter.value='';capFilter.value='';sortFilter.value='priority';renderDirectory()};
document.querySelector('#statDirectory').textContent=directory.length;
renderRanking();renderSpecialties();renderDirectory();
