const modal=document.querySelector('#modal'),modalContent=document.querySelector('#modalContent');
const PREF_KEY='aiWorldAtlasPreferencesV1';
const officialUrls={
'OpenAI':'https://openai.com/','ChatGPT':'https://chatgpt.com/','Anthropic':'https://www.anthropic.com/','Claude':'https://claude.ai/','Google DeepMind':'https://deepmind.google/','Gemini':'https://gemini.google.com/','SpaceXAI / xAI':'https://x.ai/','Grok':'https://grok.com/','Meta':'https://ai.meta.com/','Microsoft AI':'https://microsoft.ai/','Microsoft Copilot':'https://copilot.microsoft.com/','GitHub Copilot':'https://github.com/features/copilot','Amazon Web Services AI':'https://aws.amazon.com/ai/','NVIDIA':'https://www.nvidia.com/en-us/ai/','Cohere':'https://cohere.com/','Mistral AI':'https://mistral.ai/','Le Chat':'https://chat.mistral.ai/','Aleph Alpha':'https://aleph-alpha.com/','Black Forest Labs':'https://bfl.ai/','Stability AI':'https://stability.ai/','ElevenLabs':'https://elevenlabs.io/','Synthesia':'https://www.synthesia.io/','Lovable':'https://lovable.dev/','DeepSeek':'https://www.deepseek.com/','Qwen':'https://qwen.ai/','Wan':'https://wan.video/','Baidu ERNIE':'https://ernie.baidu.com/','Tencent Hunyuan':'https://hunyuan.tencent.com/','ByteDance Seed':'https://seed.bytedance.com/','Dreamina Seedance':'https://dreamina.capcut.com/','Z.ai / Zhipu AI':'https://z.ai/','Kimi':'https://www.kimi.com/','MiniMax':'https://www.minimax.io/','Huawei Pangu':'https://www.huaweicloud.com/intl/en-us/product/pangu.html','NAVER HyperCLOVA X':'https://clova.ai/','LG EXAONE':'https://www.lgresearch.ai/','Sakana AI':'https://sakana.ai/','Preferred Networks':'https://www.preferred.jp/en/','AI21 Labs':'https://www.ai21.com/','Technology Innovation Institute':'https://www.tii.ae/','G42 / Core42':'https://www.g42.ai/','Canva AI':'https://www.canva.com/ai-assistant/','Runway':'https://runwayml.com/','Midjourney':'https://www.midjourney.com/','Adobe Firefly':'https://firefly.adobe.com/','Perplexity':'https://www.perplexity.ai/','Cursor':'https://cursor.com/','Replit':'https://replit.com/','Windsurf':'https://windsurf.com/','Manus':'https://manus.im/','Poe':'https://poe.com/','Hugging Face':'https://huggingface.co/','Ideogram':'https://ideogram.ai/','Luma AI':'https://lumalabs.ai/','Pika':'https://pika.art/','Suno':'https://suno.com/','Udio':'https://www.udio.com/','Gamma':'https://gamma.app/','Notion AI':'https://www.notion.com/product/ai','Jasper':'https://www.jasper.ai/','Grammarly':'https://www.grammarly.com/ai','Character.AI':'https://character.ai/'};
const companyUrls={'Google':'https://ai.google/','Alibaba':'https://www.alibabacloud.com/en/solutions/generative-ai','Baidu':'https://www.baidu.com/','Tencent':'https://www.tencent.com/','ByteDance':'https://www.bytedance.com/','Moonshot AI':'https://www.moonshot.ai/','Huawei':'https://www.huawei.com/','NAVER':'https://www.navercorp.com/','LG AI Research':'https://www.lgresearch.ai/','TII':'https://www.tii.ae/','G42':'https://www.g42.ai/','Canva':'https://www.canva.com/','Microsoft':'https://www.microsoft.com/ai/','Amazon':'https://aws.amazon.com/ai/','Adobe':'https://www.adobe.com/ai/'};
function officialUrl(item){return item.url||officialUrls[item.name]||companyUrls[item.company]||null}
function visitBtn(item,label='Abrir IA ↗'){const url=officialUrl(item);return url?`<a class="visitBtn" href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`:''}
function loadPrefs(){try{return JSON.parse(localStorage.getItem(PREF_KEY))||{favorites:[],disliked:[]}}catch(e){return {favorites:[],disliked:[]}}}
let prefs=loadPrefs();
function savePrefs(){localStorage.setItem(PREF_KEY,JSON.stringify(prefs))}
function itemKey(item){return `${item.company}::${item.name}`}
function isFavorite(item){return prefs.favorites.includes(itemKey(item))}
function isDisliked(item){return prefs.disliked.includes(itemKey(item))}
function setPreference(item,type){const key=itemKey(item);prefs.favorites=prefs.favorites.filter(x=>x!==key);prefs.disliked=prefs.disliked.filter(x=>x!==key);if(type==='favorite')prefs.favorites.push(key);if(type==='disliked')prefs.disliked.push(key);savePrefs();renderDirectory();renderWorkAI();renderFavoritesDrawer()}
function prefControls(item){const idx=directory.indexOf(item);return `<div class="prefControls"><button class="prefBtn favorite ${isFavorite(item)?'active':''}" onclick="event.stopPropagation();setPreference(directory[${idx}],'${isFavorite(item)?'none':'favorite'}')">♥ ${isFavorite(item)?'Favorita':'Guardar'}</button><button class="prefBtn dislike ${isDisliked(item)?'active':''}" onclick="event.stopPropagation();setPreference(directory[${idx}],'${isDisliked(item)?'none':'disliked'}')">✓ ${isDisliked(item)?'No me gusta':'Descartar'}</button></div>`}
function openFavoritesDrawer(){document.querySelector('#favoritesDrawer').classList.add('show');document.querySelector('#favoritesBackdrop').classList.add('show');renderFavoritesDrawer()}
function closeFavoritesDrawer(){document.querySelector('#favoritesDrawer').classList.remove('show');document.querySelector('#favoritesBackdrop').classList.remove('show')}
function renderFavoritesDrawer(){const box=document.querySelector('#favoritesDrawerList'),badge=document.querySelector('#favoritesFloatingCount');if(!box)return;const rows=directory.filter(isFavorite);if(badge)badge.textContent=rows.length;box.innerHTML=rows.length?rows.map(x=>{const idx=directory.indexOf(x);return `<div class="drawerAI"><div class="drawerAIHead"><div><strong>${x.name}</strong><span>${x.company}</span></div><button onclick="setPreference(directory[${idx}],'none')" title="Quitar">×</button></div><p>${x.best}</p><div class="drawerActions">${visitBtn(x,'Abrir ahora ↗')}<button class="details" onclick="openDirectory(directory[${idx}])">Análisis</button></div></div>`}).join(''):`<div class="drawerEmpty"><b>Tu espacio de trabajo está vacío.</b><p>Marca ♥ en las IA que utilizas y quedarán disponibles aquí desde cualquier parte de la página.</p></div>`}
function renderWorkAI(){const box=document.querySelector('#workAIGrid'),count=document.querySelector('#workAICount');if(!box)return;const rows=directory.filter(isFavorite);if(count)count.textContent=`${rows.length} guardadas`;box.innerHTML=rows.length?rows.map(x=>{const idx=directory.indexOf(x);return `<article class="workCard"><div><div class="workHeart">♥</div><h3>${x.name}</h3><div class="sub">${x.company} · ${x.country}</div><p>${x.best}</p></div><div class="workActions">${visitBtn(x,'Abrir IA ↗')}<button class="details" onclick="openDirectory(directory[${idx}])">Análisis</button><button class="removeFav" onclick="setPreference(directory[${idx}],'none')">Quitar</button></div></article>`}).join(''):`<div class="empty"><strong>Aún no tienes IA guardadas.</strong><br>Marca el corazón ♥ de cualquier herramienta del directorio.</div>`}
function openRanking(item){modalContent.innerHTML=`<div class="label">Puesto ${item.rank} de la clasificación general</div><h2>${item.name}</h2><div class="company">${item.company} · ${item.country}</div><div class="scoreRow"><div><div class="level">${item.level}</div><div style="margin-top:6px;color:#667085;font-size:12px">Puntuación editorial global</div></div><div class="scoreBig">${item.score}<span style="font-size:13px;color:#98a2b3">/100</span></div></div><div class="detailBlock"><h4>Modelo principal</h4><p>${item.model}</p></div><div class="detailBlock"><h4>Mejor para</h4><p>${item.best}</p></div><div class="detailBlock"><div class="procon"><div><b>Fortalezas</b><p>${item.strengths}</p></div><div><b>Limitaciones</b><p>${item.limits}</p></div></div></div><div class="detailBlock"><h4>Por qué ocupa este puesto</h4><p>${item.why}</p></div><div class="detailBlock"><h4>Referencia independiente</h4><p>${item.aa}</p></div>`;modal.classList.add('show');document.body.style.overflow='hidden'}
function openDirectory(item){modalContent.innerHTML=`<div class="label">${item.class}</div><h2>${item.name}</h2><div class="company">${item.company} · ${item.country}</div><div class="modalActions">${visitBtn(item,'Ir al sitio oficial ↗')}</div>${prefControls(item)}<div class="detailBlock"><h4>Qué es</h4><p>${item.desc}</p></div><div class="detailBlock"><h4>Su mayor fortaleza</h4><p>${item.best}</p></div><div class="detailBlock"><h4>Modelos o tecnología principal</h4><p>${item.model}</p></div><div class="detailBlock"><h4>Apertura</h4><p>${item.open}</p></div><div class="detailBlock"><h4>Capacidades</h4><div class="tags">${item.caps.map(x=>`<span class="tag">${x}</span>`).join('')}</div></div>`;modal.classList.add('show');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('show');document.body.style.overflow=''}
document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#backdrop').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeFavoritesDrawer()}});
function renderRanking(){document.querySelector('#rankingList').innerHTML=ranking.map((x,i)=>`<article class="rankCard"><div class="rankNo ${i<3?'top':''}">#${x.rank}</div><div class="rankName"><h3>${x.name}</h3><p>${x.company} · ${x.model.split(';')[0]}</p><div class="rankMeta"><span class="level">${x.level}</span></div></div><div class="score">${x.score}<small>/100</small></div><div class="rankWhy"><strong style="color:#344054">Su fuerte:</strong> ${x.best}</div><button class="openBtn" onclick="openRanking(ranking[${i}])">Análisis</button></article>`).join('')}
let activeSpecialty=Object.keys(specialties)[0];function renderSpecialties(){const tabs=document.querySelector('#specialtyTabs');tabs.innerHTML=Object.keys(specialties).map(x=>`<button class="tab ${x===activeSpecialty?'active':''}" onclick="activeSpecialty='${x}';renderSpecialties()">${x}</button>`).join('');document.querySelector('#specialGrid').innerHTML=specialties[activeSpecialty].map(x=>`<article class="specialCard"><div class="pos">Puesto ${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><div class="metric">${x[3]}</div></article>`).join('')}
const search=document.querySelector('#search'),classFilter=document.querySelector('#classFilter'),regionFilter=document.querySelector('#regionFilter'),capFilter=document.querySelector('#capFilter'),sortFilter=document.querySelector('#sortFilter');[...new Set(directory.map(x=>x.region))].sort().forEach(x=>regionFilter.innerHTML+=`<option>${x}</option>`);[...new Set(directory.flatMap(x=>x.caps))].sort().forEach(x=>capFilter.innerHTML+=`<option>${x}</option>`);
function renderDirectory(){let s=search.value.trim().toLowerCase(),c=classFilter.value,r=regionFilter.value,k=capFilter.value;let rows=directory.filter(x=>(!s||JSON.stringify(x).toLowerCase().includes(s))&&(!c||x.class===c)&&(!r||x.region===r)&&(!k||x.caps.includes(k)));if(sortFilter.value==='priority'){const p={'Modelo propio':0,'Híbrida':1,'Aplicación sobre terceros':2};rows.sort((a,b)=>p[a.class]-p[b.class]||a.name.localeCompare(b.name))}else if(sortFilter.value==='name')rows.sort((a,b)=>a.name.localeCompare(b.name));else rows.sort((a,b)=>a.country.localeCompare(b.country)||a.name.localeCompare(b.name));document.querySelector('#resultCount').textContent=`${rows.length} resultados · ${prefs.favorites.length} favoritas`;document.querySelector('#directoryGrid').innerHTML=rows.length?rows.map(x=>{const idx=directory.indexOf(x);return `<article class="card ${isFavorite(x)?'isFavorite':''} ${isDisliked(x)?'isDisliked':''}"><div class="cardTop"><div class="avatar">${x.name.replace(/[^A-Za-zÁÉÍÓÚÑ]/g,'').slice(0,2).toUpperCase()}</div><span class="type">${x.class}</span></div><h3>${x.name}</h3><div class="sub">${x.company}</div><p class="desc">${x.desc}</p><p class="best"><strong>Mejor para:</strong> ${x.best}</p><div class="tags">${x.caps.slice(0,5).map(y=>`<span class="tag">${y}</span>`).join('')}</div>${prefControls(x)}<div class="cardFooter"><span class="country">${x.country}</span><div class="cardLinks">${visitBtn(x,'Abrir ↗')}<button class="details" onclick="openDirectory(directory[${idx}])">Análisis →</button></div></div></article>`}).join(''):`<div class="empty">No hay resultados con estos filtros.</div>`}
[search,classFilter,regionFilter,capFilter,sortFilter].forEach(el=>el.addEventListener(el===search?'input':'change',renderDirectory));document.querySelector('#clearFilters').onclick=()=>{search.value='';classFilter.value='';regionFilter.value='';capFilter.value='';sortFilter.value='priority';renderDirectory()};document.querySelector('#statDirectory').textContent=directory.length;
renderRanking();renderSpecialties();renderDirectory();renderWorkAI();renderFavoritesDrawer();